In [13]:
# Until now, the assistant only has the knowledge that was used to train those models.
# The original goal that we set uout to do was make a research paper assistant.
# So the llm will only have knowledge about the research papers until a specific point in time.
# What if I want to give it more knowledge about the research papers that were published after that point in time?
# I can use the retrieval augmented generation (RAG) approach to give the assistant access to the latest research papers.

In [14]:
# I will not go into the typical definition of RAG; but instead start with what are the building blocks of RAG.
# I will add each block one by one and then show how to put them together to create a RAG pipeline.
# The foundational building blocks of RAG are:
# - Document extraction
# - Chunking
# - Embedding
# - Indexing into Vector database
# - Retrieval
# - Generation

In [15]:
# On top of the foundational building blocks, 
# we can also add some additional blocks to make the RAG pipeline more robust and efficient.

# Additional building blocks of RAG are:
# - Query Analysis
# - Re-ranking
# - Validation
# - Feedback loop

In [16]:
# Tools, Agents and RAG are not mutually exclusive.
# We can use tools and agents in the RAG pipeline to make it even more efficient and robust; 
# but I'll pick it up after we have successfully implemented RAG pipeline without tools and agents.

In [17]:
# Langchain and Langgraph are my personal choice of building RAG pipelines.
# I will add code blocks for each of the building blocks of RAG using Langchain.
# And then I will show how to put them together to create a RAG pipeline or workflow using Langgraph.

In [18]:
# There are some important imports in langchain.

In [19]:
from langchain_community.document_loaders import TextLoader, PyPDFLoader, UnstructuredPDFLoader

# TextLoader is used to load text files, PyPDFLoader is used to load pdf files.
# UnstructuredPDFLoader is used to load pdf files using unstructured.io library which relies more on deep learning models.

In [20]:
# Lets start simple to complex. Our goal is to load the file, parse the content in readable format and display it.

# Order of complexity of files:
# .txt file
# pdf file containing only text
# pdf file containing text and tables
# pdf file containing text and tables and images
# pdf file containing text and tables and images and urls
# pdf file containing text and tables and images and urls and mathematical equations / latex

In [21]:
# SOURCE DOCUMENTS :

# .txt file
# Create text file from : https://en.wikipedia.org/wiki/Hindustan_Socialist_Republican_Association

# pdf file containing only text
# Download file from : https://s21.q4cdn.com/399680738/files/doc_financials/2025/q2/META-Q2-2025-Earnings-Call-Transcript.pdf

# pdf file containing text and tables
# Download file from : https://www.jpmorganchase.com/content/dam/jpmc/jpmorgan-chase-and-co/investor-relations/documents/annualreport-2024.pdf

# pdf file containing text and tables and images
# Download file from : https://www.nestle.in/sites/g/files/pydnoa451/files/2025-06/Nestl%C3%A9-India-AR-2024-25.pdf

# pdf file containing text and tables and images and urls
# Download file from : https://arxiv.org/abs/1706.03762

# pdf file containing text and tables and images and urls and mathematical equations / latex
# Download file from : https://upload.wikimedia.org/wikipedia/commons/8/81/Algorithms.pdf

In [22]:
data_directory = "../assets/data/" # Setting up a common data directory where I'll paste all documents for notebooks only

In [23]:
# Load : 
# # .txt file

In [24]:
from langchain_community.document_loaders import TextLoader

In [25]:
loader = TextLoader(file_path=data_directory+"HRA.txt")

In [26]:
documents = await loader.aload()

In [27]:
print(documents)

[Document(metadata={'source': '../assets/data/HRA.txt'}, page_content='Hindustan Socialist Republican Association\nFrom Wikipedia, the free encyclopedia\n\nHindustan Socialist Republican Association (HSRA), previously known as the Hindustan Republican Army and Hindustan Republican Association (HRA), was a left-wing Indian revolutionary organization, founded by Sachindranath Sanyal. After changes in Bhagat Singh\'s ideology and the influence of the Russian Revolution, they held meetings in Feroz Shah Kotla Maidan and added the word socialist to their name. Ram Prasad Bismil, Ashfaqulla Khan, Sachindra Nath Bakshi, Sachindranath Sanyal and Jogesh Chandra Chatterjee were the leaders of the group at the time. HSRA\'s manifesto titled The Revolutionary and written constitution were produced as evidence in the Kakori conspiracy case of 1925. \n\nOrigins\nBackground\nThe non-cooperation movement of 1919 had led to a large-scale mobilization of the Indian population against the British Raj. Although intended as a non-violent resistance movement, due to heightened tensions, and a brutal response by the British police forces, it had soon become violent. After the Chauri Chaura incident, where several police officers were locked in a police station, which was subsequently set on fire by demonstrators, Mahatma Gandhi suspended the movement to prevent the escalation of violence. This disillusioned a section of nationalists who felt the suspension was premature and unwarranted. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the 37th session of the Indian National Congress, held in Gaya, Bihar.[4] The political vacuum created by the suspension led to the formation of revolutionary movements by the more radical amongst those who sought to overthrow British Raj.\n\nOpposition of Gandhi in Gaya Congress\nIn February 1922, some agitating farmers were killed in Chauri Chaura by the police. Consequently, the police station of Chauri Chaura was attacked by the people and 22 policemen were burnt alive. \nWithout ascertaining the facts behind this incident, Mahatma Gandhi, declared an immediate stop to the Non-cooperation movement (he himself had given a call for it) without consulting any executive committee member of the Congress. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the Gaya Congress of 1922. When Gandhi refused to rescind his decision, the Indian National Congress was divided into two groups – one liberal and the other for rebellion. In January 1923, the liberal group formed a new Swaraj Party under the joint leadership of Moti Lal Nehru and Chittaranjan Das, and the youth group formed a revolutionary party under the leadership of Bismil.\nYellow Paper constitution\n\nWith the consent of Lala Har Dayal, Bismil went to Allahabad where he drafted the constitution of the party in 1923 with the help of Sachindra Nath Sanyal and another revolutionary of Bengal, Dr. Jadugopal Mukherjee.[6][full citation needed] The basic name and aims of the organisation were typed on a Yellow Paper and later on a subsequent Constitutional Committee Meeting was conducted on 3 October 1924 at Cawnpore in the United Provinces under Sanyal\'s chairmanship.\nSharing responsibility\n\nThis meeting decided the name of the party would be the Hindustan Republican Association (HRA). Bismil was declared the District Organiser for Shahjahanpur and chief of arms division, as well as provincial organiser of United Provinces. Sachindra Nath Sanyal became National Organiser and another senior member, Jogesh Chandra Chatterjee, was Coordinator of the Anushilan Samiti. After attending the meeting in Cawnpore, both Sanyal and Chatterjee left the United Province and proceeded to Bengal for further extension of the organisation.[citation needed]\n\nThe HRA established branches in Agra, Allahabad, Benares, Cawnpore, Lucknow, Saharanpur and Shahjahanpur. They also manufactured bombs in Calcutta – at Dakshineswar and Shovabazar and at Deoghar in Jharkhand (then Bihar province). The Calcutta workshops were discovered by the police in 1925 and those in Deoghar were found in 1927.[5]\nPublication of Revolutionary\n\nSanyal wrote a manifesto for the HRA entitled Revolutionary. This was distributed around large cities of North India on 1 January 1925.[7] It proposed the overthrow of British colonial rule and its replacement with what it termed a Federal Republic of the United States of India. In addition, it sought universal suffrage and the socialist-oriented aim of the abolition of "all systems which make any kind of exploitation of man by man possible"[5]\n\nThe policies of Gandhi were criticised and youths were called to join the organisation. The police were astonished to see the language used and sought its leader in Bengal. Sanyal had gone to despatch this pamphlet in bulk and was arrested in Bankura, West Bengal. Before Sanyal\'s arrest, Jogesh Chandra Chatterjee had also been caught by police at Howrah railway station of Calcutta, Bengal Presidency.\nEarly activities\nWall painting of Bhagat Singh; Rewalsar, India, 2009\n\nThere were many early attempts at disruption and obtaining funds, such as the robbery of the houses of a village officials at Dwarikapur and Bichpuri in 1922–23, but the Kakori train robbery was the most prominent of the early HRA efforts. The Kakori event occurred on 9 August 1925, when HRA members looted government money from a train around 10 miles (16 km) from Lucknow and accidentally killed a passenger in the process. Significant members of the HRA were arrested and tried for their involvement in that incident and others which had preceded it. The outcome was that four leaders – Ashfaqullah Khan, Ram Prasad Bismil, Roshan Singh and Rajendra Lahiri – were hanged in December 1927 and a further 16 imprisoned for lengthy terms. The result of the trial, in which the HRA participants sang patriotic songs and displayed other forms of defiance, seriously damaged the leadership of the HRA and dealt a major blow to its activities. Many associated with the HRA who escaped trial found themselves placed under surveillance or detained for various reasons. Chandra Shekhar Azad was the only one of the principal leaders who managed to escape arrest whereas Banwari Lal became an approver.[5]\nMajor activities\n\nIn 1928, the British government set up the Commission, headed by Sir John Simon, to report on the political situation in India. Some Indian activist groups protested the commission, because it did not include a single Indian in its membership, although by no means all did so. The effect was to unite various activist factions in opposition.[8]\n\nResponding to the rise in anti-colonial sentiment in 1928,[8] the HRA became the Hindustan Socialist Republican Association, with the change of name probably being largely due to the influence of Bhagat Singh.[9] Around the time of the Kakori robbery and the subsequent trial, various revolutionary groups had emerged in places such as Bengal, Bihar, and Punjab. These groups and the HRA met at Feroz Shah Kotla, in Delhi, on 8–9 September 1928, and from this emerged the HSRA.[a] The socialist leanings voiced in the earlier HRA manifesto had gradually moved more towards Marxism and the HSRA spoke of a revolution involving a struggle by the masses to establish "the dictatorship of the proletariat" and the banishment of "parasites from the seat of political power". It saw itself as being at the forefront of this revolution, spreading the word and acting as the armed section of the masses. Its ideals were apparent in other movements elsewhere at that time, including incidents of communist-inspired industrial action by workers and the rural kisan movement.[5] At the request of Bhagat Singh, the newly named HSRA resolved to bomb members of the Simon Commission and also to cease robbing rich people, the latter being a realisation that the Kakori conspirators had suffered most from the evidence given by such people.[8] At that time the HRA was being transformed into the HSRA and it was decided that the new organization would work in cooperation with the Communist International.\n\nThe HSRA\'s manifesto titled Philosophy of the Bomb was written by Bhagwati Charan Vohra.[10]\nKilling of John P. Saunders\n\nWhen the Simon Commission visited Lahore on 30 October 1928, Lala Lajpat Rai led a peaceful protest against the commission. The police responded with violence, with the Superintendent of Police, James A. Scott, ordering his men to lathi charge the protesters. Rai was beaten but addressed a meeting later. He died on 17 November 1928, perhaps in part because of his injuries although this is uncertain. Historian Neeti Nair says "His death was widely attributed to the mental if not physical shock he had suffered."[8] When the matter of Lala Lajpat Rai\'s death was raised in the British Parliament, the government denied any causal role.[11] Bhagat Singh vowed to take revenge,[11] and joined other revolutionaries, Shivaram Rajguru, Jai Gopal, Sukhdev Thapar and Chandra Shekhar Azad, in a plot to kill Scott.[5] However, in a case of mistaken identity, Singh was signalled to shoot on the appearance of John P. Saunders, an Assistant superintendent. He was shot by Rajguru and Singh while leaving the District Police Headquarters in Lahore on 17 December 1928.[12] Chanan Singh, a Head Constable who was chasing them, was killed by Azad\'s covering fire.[13]\n\nThis case of mistaken identity did not stop Singh and his fellow-members of the HSRA from claiming that retribution had been exacted.[5] The next day the HSRA acknowledged the assassination by putting up posters in Lahore that read\n\n    J. P. Saunders is dead; Lala Lajpat Rai is avenged. ... In this man has died an agent of the British authority in India. ... Sorry for the bloodshed of the human being, but the sacrifice of individuals at the altar of revolution ... is inevitable.[14]\n\nFront page of the Tribune (25 March 1931) published from Lahore, reporting the execution of Singh, Sukhdev & Rajguru\n\nThe perpetrators of the Saunders murder having eluded capture and gone into hiding, the next major action by the HSRA was the bombing of the Central Legislative Assembly in Delhi on 8 April 1929. This was a provocative propaganda exercise, intended to highlight the aims of the HSRA and timed as a protest against the introduction of the Public Safety Bill and the Trade Disputes Bill, both of which had been drafted in an attempt to counter the effects of communist activities and trade unionism[5][15]\n\nSingh and Batukeshwar Dutt threw bombs at the empty benches, being careful to ensure that there were no casualties in order to highlight the propagandist nature of their action. They made no attempt to escape and courted arrest while shouting Inquilab Zindabad (Long Live the Revolution), Vande Mataram (Hail to motherland) and Samrajyavad Murdabad\' (Down with Imperialism). Their rationale for the bombing was explained in a leaflet titled "To Make the Deaf Hear" (paraphrasing the words of Édouard Vaillant). This leaflet was also thrown in the assembly and was reproduced the next day in the Hindustan Times. On 15 April 1929, police raided the HSRA\'s bomb factory in Lahore and arrested Kishori Lal, Sukhdev and Jai Gopal. The Assembly Bomb case and the Saunders murder case trial followed and Singh, Sukhdev and Rajguru were hanged on 23 March 1931 for their actions.[5][15]\nLater activities\n\nIn December 1929, the HSRA bombed the special train of Lord Irwin. The Viceroy escaped unhurt. Later, the Lahore faction of HSRA broke away and formed the Atishi Chakar (The Ring of Fire) party under the leadership of Hans Raj Vohra. They carried out a series of bombings across Punjab in June 1929. On 21 January 1929, Bhagat Singh and his fellow comrades were accused in the Lahore Conspiracy Case, appeared in the court wearing red scarves. As soon as the magistrate took his chair, they raised slogans "Long Live Socialist Revolution", "Long Live Communist International", "Long Live People" "Lenin\'s Name Will Never Die", and "Down with Imperialism".[16][17] On 1 September 1929, the Rawalpindi faction made a failed attempt to burgle the Office of the Controller of Military Accounts. During this period the leading members of the HSRA were Chandra Shekhar Azad, Yashpal, Bhagwati Charan Vohra and Kailash Pati. In July 1929, the HSRA robbed the Gadodia stores in New Delhi and carried away 14,000 rupees. This money was later used to fund a bomb factory. In December 1929, an attempt was made to assassinate the Governor of Punjab, which wounded him in his arm.[18]\nDecline\n\nBy 1930, most of the HSRA\'s main leaders were either dead or in prison. Kailash Pati was arrested in October 1929 and turned an approver (witness for the prosecution). On 27 February 1931, Chandra Shekhar Azad shot himself in the head during a gunfight with the Allahabad Police in a famous incident of Alfred Park. Bhagat Singh, Sukhdev Thapar, and Shivaram Rajguru were hanged on 23 March 1931. After Azad\'s death, there was no central leader to unite the revolutionaries and regional differences increased. The organisation split into various regional groups and they carried out bombings and attacks on British officials in India without any central coordination. In December 1930, another attempt was made to revive the HSRA at a meeting in Meerut. However, this attempt failed with the arrests of Yashpal and Daryao Singh in 1931.[19] This effectively ended the HSRA as a united organisation though the various regional factions kept up their armed struggle until 1935.\nCriticism\n\nThe association\'s methods were diametrically opposite to that of Gandhi\'s nonviolent resistance movement. The revolutionaries and their methods were severely criticized by Gandhi. Responding to the attack on Lord Irwin\'s train, Gandhi wrote a harsh critique of the HSRA titled "The Cult of the Bomb" (Young India, 2 January 1929). In it, he declared that bomb-throwing was nothing but "froth coming to the surface in an agitated liquid". He condemned the HSRA and its actions as "cowards" and "dastardly". According to Gandhi, the HSRA\'s violent struggle had its hazards. The violence led to more reprisals and suffering. Also, it would turn inward as "it was an easy natural step" from "violence done to the foreign ruler" to "violence to our own people".[20] The HSRA responded to this criticism with its own manifesto "The Philosophy of the Bomb",[10] in which they defended their violent methods as being complementary to Gandhi\'s non-violent methods.[21]\nProminent members\nName \tInvolved in \tOutcome\nChandra Shekhar Azad \tKakori conspiracy, John P. Saunders assassination (1927) \tAbsconded in the Kakori Conspiracy Case, while living underground he re-organized the HSRA and shot himself dead in a shoot-out with police at Allahabad on 27 February 1931.[22]\nSachindra Nath Bakshi \tKakori conspiracy \tSentenced to life imprisonment in Kakori case; released in 1936 and became active in Congress but left the party after independence. He was elected as the MLA on Jan Sangh Party ticket[23]\nSuresh Chandra Bhattacharya \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case[22]\nRam Prasad Bismil \tMainpuri conspiracy (1917) and Kakori conspiracy[24] \tAbsconded in Mainpuri case; Sentenced to death in Kakori case.[citation needed] Hanged in 1926 at Gorakhpur Central Jail\nJogesh Chandra Chatterjee \tKakori conspiracy \tSentenced to life imprisonment in Kakori case; became a Member of Parliament after independence\nPranawesh Chatterjee \tKakori conspiracy \tSentenced to four years\' rigorous imprisonment in Kakori case[22]\nVishnu Sharan Dublish \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori conspiracy which was converted later into a life sentence after Naini Jail Case.[22] Joined Indian National Congress, freedom movement activities in Western Uttar Pradesh, became a member of parliament.\nManmath Nath Gupta \tKakori conspiracy \tSentenced to 14 years\' rigorous imprisonment in Kakori case; later became a journalist/writer; died in 1999 on the day of Deepavali.\nGovind Charan Kar \tKakori conspiracy \tSentenced to life in Kakori case.\nAshfaqulla Khan \tKakori conspiracy \tSentenced to death in Kakori case.[25] Hanged in 1926 at Faizabad Jail.\nPrem Krishna Khanna \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case.[22] He became a Member of Parliament from Shahjahanpur[26] in 1961 and 1966.\nRam Krishna Khatri \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case.[22]\nRajendra Nath Lahiri \tKakori conspiracy \tSentenced to death in Kakori case.[citation needed] Hanged in 1926 at Gonda Jail.\nBanwari Lal \tKakori conspiracy \tSentenced to two years\' even after being an approver in the Kakori case.[22]\nMukundi Lal \tMainpuri conspiracy (1917) and Kakori conspiracy[27] \tSentenced to seven years\' rigorous imprisonment in Mainpuri and life in Kakori conspiracy case; died in October 1981.[28]\nRam Nath Pandey \tKakori conspiracy \tSentenced to three years\' rigorous imprisonment in Kakori case.[22]\nBhupendra Nath Sanyal \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case[22]\nSachindra Nath Sanyal \tKakori conspiracy \tSentenced to life imprisonment in Andaman Cellular Jail; died of tuberculosis at Bhowali TB sanatorium in 1942.\nThakur Roshan Singh \tKakori conspiracy \tSentenced to death in Kakori case.[citation needed] Hanged in 1926 at Allahabad Jail.\nRaj Kumar Sinha \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case.[22]\nRam Dulare Trivedi \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case.[22]\nAjoy Ghosh \tLahore Conspiracy Case trial \tHe was arrested and latter imprisoned after Lahore Conspiracy Case trial in 1928 but released due to lack of evidence. Later, he joined Communist Party of India and become general secretary of CPI in 1950.\nEnd time and Dissolution\n\nAfter the death of Bhagat Singh and Chandra Shekhar Azad, another associate Udham Singh operated the HSRA from London. HSRA was dissolved in 1940 when Udham was hanged.\nLegacy\n\nA bomb factory and hideout located in Turi Bazaar, Firozpur, has been declared as a national monument by the Government of Punjab.[29]\nSee also\n\n    Sushila Didi\n    Ashfaqulla Khan\n    Delhi Conspiracy Commission\n    Naujawan Bharat Sabha\n    Revolutionary movement for Indian independence\n    Workers and Peasants Party\n\nReferences\n\nNotes\n\n    The revolutionary group from Bengal did not formally associate itself with the HSRA in 1928 but did provide Jatindra Nath Das to give advice on explosives. The Bengal group did not accept the socio-economic aspects of revolution proposed by the other groups and preferred to see it purely in terms of nationalism.[5]\n\nReferences\n\n    "To Young Political Workers". Archived from the original on 1 October 2015. Retrieved 11 March 2024.\n    "The Red Pamphlet". Archived from the original on 26 February 2024. Retrieved 26 February 2024.\n    "Ashfaqulla Khan: An epitome of Hindu-Muslim Unity and inspiration for the Youth".[permanent dead link]\n    Indian National Congress (1919). Report Of The Thirty Third Session Of The Indian National Congress. Delhi: L.M.H Press.\n    Gupta (1997)\n    Dr. Mehrotra N.C. Swatantrata Andolan Mein Shahjahanpur Ka Yogdan Page 109 & 146\n    Balinisteanu, Tudor (2012). Violence, Narrative and Myth in Joyce and Yeats: Subjective Identity and Anarcho-Syndicalist Traditions. Palgrave Macmillan. p. 60. ISBN 978-0-23029-095-2.[permanent dead link]\n    Nair (2009)\n    Sawhney (2012), p. 380\n    Bowden & Davis (2009), p. 29\n    Rana (2005a), p. 36\n    Nayar (2000), p. 39\n    Rana (2005b), p. 65\n    Grewal (2007), p. 46\n    Singh, Lala & Hooja (2007), pp. 16–18\n    Khan,

In [28]:
len(documents)

1

In [29]:
documents[0]

Document(metadata={'source': '../assets/data/HRA.txt'}, page_content='Hindustan Socialist Republican Association\nFrom Wikipedia, the free encyclopedia\n\nHindustan Socialist Republican Association (HSRA), previously known as the Hindustan Republican Army and Hindustan Republican Association (HRA), was a left-wing Indian revolutionary organization, founded by Sachindranath Sanyal. After changes in Bhagat Singh\'s ideology and the influence of the Russian Revolution, they held meetings in Feroz Shah Kotla Maidan and added the word socialist to their name. Ram Prasad Bismil, Ashfaqulla Khan, Sachindra Nath Bakshi, Sachindranath Sanyal and Jogesh Chandra Chatterjee were the leaders of the group at the time. HSRA\'s manifesto titled The Revolutionary and written constitution were produced as evidence in the Kakori conspiracy case of 1925. \n\nOrigins\nBackground\nThe non-cooperation movement of 1919 had led to a large-scale mobilization of the Indian population against the British Raj. Although intended as a non-violent resistance movement, due to heightened tensions, and a brutal response by the British police forces, it had soon become violent. After the Chauri Chaura incident, where several police officers were locked in a police station, which was subsequently set on fire by demonstrators, Mahatma Gandhi suspended the movement to prevent the escalation of violence. This disillusioned a section of nationalists who felt the suspension was premature and unwarranted. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the 37th session of the Indian National Congress, held in Gaya, Bihar.[4] The political vacuum created by the suspension led to the formation of revolutionary movements by the more radical amongst those who sought to overthrow British Raj.\n\nOpposition of Gandhi in Gaya Congress\nIn February 1922, some agitating farmers were killed in Chauri Chaura by the police. Consequently, the police station of Chauri Chaura was attacked by the people and 22 policemen were burnt alive. \nWithout ascertaining the facts behind this incident, Mahatma Gandhi, declared an immediate stop to the Non-cooperation movement (he himself had given a call for it) without consulting any executive committee member of the Congress. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the Gaya Congress of 1922. When Gandhi refused to rescind his decision, the Indian National Congress was divided into two groups – one liberal and the other for rebellion. In January 1923, the liberal group formed a new Swaraj Party under the joint leadership of Moti Lal Nehru and Chittaranjan Das, and the youth group formed a revolutionary party under the leadership of Bismil.\nYellow Paper constitution\n\nWith the consent of Lala Har Dayal, Bismil went to Allahabad where he drafted the constitution of the party in 1923 with the help of Sachindra Nath Sanyal and another revolutionary of Bengal, Dr. Jadugopal Mukherjee.[6][full citation needed] The basic name and aims of the organisation were typed on a Yellow Paper and later on a subsequent Constitutional Committee Meeting was conducted on 3 October 1924 at Cawnpore in the United Provinces under Sanyal\'s chairmanship.\nSharing responsibility\n\nThis meeting decided the name of the party would be the Hindustan Republican Association (HRA). Bismil was declared the District Organiser for Shahjahanpur and chief of arms division, as well as provincial organiser of United Provinces. Sachindra Nath Sanyal became National Organiser and another senior member, Jogesh Chandra Chatterjee, was Coordinator of the Anushilan Samiti. After attending the meeting in Cawnpore, both Sanyal and Chatterjee left the United Province and proceeded to Bengal for further extension of the organisation.[citation needed]\n\nThe HRA established branches in Agra, Allahabad, Benares, Cawnpore, Lucknow, Saharanpur and Shahjahanpur. They also manufactured bombs in Calcutta – at Dakshineswar and Shovabazar and at Deoghar in Jharkhand (then Bihar province). The Calcutta workshops were discovered by the police in 1925 and those in Deoghar were found in 1927.[5]\nPublication of Revolutionary\n\nSanyal wrote a manifesto for the HRA entitled Revolutionary. This was distributed around large cities of North India on 1 January 1925.[7] It proposed the overthrow of British colonial rule and its replacement with what it termed a Federal Republic of the United States of India. In addition, it sought universal suffrage and the socialist-oriented aim of the abolition of "all systems which make any kind of exploitation of man by man possible"[5]\n\nThe policies of Gandhi were criticised and youths were called to join the organisation. The police were astonished to see the language used and sought its leader in Bengal. Sanyal had gone to despatch this pamphlet in bulk and was arrested in Bankura, West Bengal. Before Sanyal\'s arrest, Jogesh Chandra Chatterjee had also been caught by police at Howrah railway station of Calcutta, Bengal Presidency.\nEarly activities\nWall painting of Bhagat Singh; Rewalsar, India, 2009\n\nThere were many early attempts at disruption and obtaining funds, such as the robbery of the houses of a village officials at Dwarikapur and Bichpuri in 1922–23, but the Kakori train robbery was the most prominent of the early HRA efforts. The Kakori event occurred on 9 August 1925, when HRA members looted government money from a train around 10 miles (16 km) from Lucknow and accidentally killed a passenger in the process. Significant members of the HRA were arrested and tried for their involvement in that incident and others which had preceded it. The outcome was that four leaders – Ashfaqullah Khan, Ram Prasad Bismil, Roshan Singh and Rajendra Lahiri – were hanged in December 1927 and a further 16 imprisoned for lengthy terms. The result of the trial, in which the HRA participants sang patriotic songs and displayed other forms of defiance, seriously damaged the leadership of the HRA and dealt a major blow to its activities. Many associated with the HRA who escaped trial found themselves placed under surveillance or detained for various reasons. Chandra Shekhar Azad was the only one of the principal leaders who managed to escape arrest whereas Banwari Lal became an approver.[5]\nMajor activities\n\nIn 1928, the British government set up the Commission, headed by Sir John Simon, to report on the political situation in India. Some Indian activist groups protested the commission, because it did not include a single Indian in its membership, although by no means all did so. The effect was to unite various activist factions in opposition.[8]\n\nResponding to the rise in anti-colonial sentiment in 1928,[8] the HRA became the Hindustan Socialist Republican Association, with the change of name probably being largely due to the influence of Bhagat Singh.[9] Around the time of the Kakori robbery and the subsequent trial, various revolutionary groups had emerged in places such as Bengal, Bihar, and Punjab. These groups and the HRA met at Feroz Shah Kotla, in Delhi, on 8–9 September 1928, and from this emerged the HSRA.[a] The socialist leanings voiced in the earlier HRA manifesto had gradually moved more towards Marxism and the HSRA spoke of a revolution involving a struggle by the masses to establish "the dictatorship of the proletariat" and the banishment of "parasites from the seat of political power". It saw itself as being at the forefront of this revolution, spreading the word and acting as the armed section of the masses. Its ideals were apparent in other movements elsewhere at that time, including incidents of communist-inspired industrial action by workers and the rural kisan movement.[5] At the request of Bhagat Singh, the newly named HSRA resolved to bomb members of the Simon Commission and also to cease robbing rich people, the latter being a realisation that the Kakori conspirators had suffered most from the evidence given by such people.[8] At that time the HRA was being transformed into the HSRA and it was decided that the new organization would work in cooperation with the Communist International.\n\nThe HSRA\'s manifesto titled Philosophy of the Bomb was written by Bhagwati Charan Vohra.[10]\nKilling of John P. Saunders\n\nWhen the Simon Commission visited Lahore on 30 October 1928, Lala Lajpat Rai led a peaceful protest against the commission. The police responded with violence, with the Superintendent of Police, James A. Scott, ordering his men to lathi charge the protesters. Rai was beaten but addressed a meeting later. He died on 17 November 1928, perhaps in part because of his injuries although this is uncertain. Historian Neeti Nair says "His death was widely attributed to the mental if not physical shock he had suffered."[8] When the matter of Lala Lajpat Rai\'s death was raised in the British Parliament, the government denied any causal role.[11] Bhagat Singh vowed to take revenge,[11] and joined other revolutionaries, Shivaram Rajguru, Jai Gopal, Sukhdev Thapar and Chandra Shekhar Azad, in a plot to kill Scott.[5] However, in a case of mistaken identity, Singh was signalled to shoot on the appearance of John P. Saunders, an Assistant superintendent. He was shot by Rajguru and Singh while leaving the District Police Headquarters in Lahore on 17 December 1928.[12] Chanan Singh, a Head Constable who was chasing them, was killed by Azad\'s covering fire.[13]\n\nThis case of mistaken identity did not stop Singh and his fellow-members of the HSRA from claiming that retribution had been exacted.[5] The next day the HSRA acknowledged the assassination by putting up posters in Lahore that read\n\n    J. P. Saunders is dead; Lala Lajpat Rai is avenged. ... In this man has died an agent of the British authority in India. ... Sorry for the bloodshed of the human being, but the sacrifice of individuals at the altar of revolution ... is inevitable.[14]\n\nFront page of the Tribune (25 March 1931) published from Lahore, reporting the execution of Singh, Sukhdev & Rajguru\n\nThe perpetrators of the Saunders murder having eluded capture and gone into hiding, the next major action by the HSRA was the bombing of the Central Legislative Assembly in Delhi on 8 April 1929. This was a provocative propaganda exercise, intended to highlight the aims of the HSRA and timed as a protest against the introduction of the Public Safety Bill and the Trade Disputes Bill, both of which had been drafted in an attempt to counter the effects of communist activities and trade unionism[5][15]\n\nSingh and Batukeshwar Dutt threw bombs at the empty benches, being careful to ensure that there were no casualties in order to highlight the propagandist nature of their action. They made no attempt to escape and courted arrest while shouting Inquilab Zindabad (Long Live the Revolution), Vande Mataram (Hail to motherland) and Samrajyavad Murdabad\' (Down with Imperialism). Their rationale for the bombing was explained in a leaflet titled "To Make the Deaf Hear" (paraphrasing the words of Édouard Vaillant). This leaflet was also thrown in the assembly and was reproduced the next day in the Hindustan Times. On 15 April 1929, police raided the HSRA\'s bomb factory in Lahore and arrested Kishori Lal, Sukhdev and Jai Gopal. The Assembly Bomb case and the Saunders murder case trial followed and Singh, Sukhdev and Rajguru were hanged on 23 March 1931 for their actions.[5][15]\nLater activities\n\nIn December 1929, the HSRA bombed the special train of Lord Irwin. The Viceroy escaped unhurt. Later, the Lahore faction of HSRA broke away and formed the Atishi Chakar (The Ring of Fire) party under the leadership of Hans Raj Vohra. They carried out a series of bombings across Punjab in June 1929. On 21 January 1929, Bhagat Singh and his fellow comrades were accused in the Lahore Conspiracy Case, appeared in the court wearing red scarves. As soon as the magistrate took his chair, they raised slogans "Long Live Socialist Revolution", "Long Live Communist International", "Long Live People" "Lenin\'s Name Will Never Die", and "Down with Imperialism".[16][17] On 1 September 1929, the Rawalpindi faction made a failed attempt to burgle the Office of the Controller of Military Accounts. During this period the leading members of the HSRA were Chandra Shekhar Azad, Yashpal, Bhagwati Charan Vohra and Kailash Pati. In July 1929, the HSRA robbed the Gadodia stores in New Delhi and carried away 14,000 rupees. This money was later used to fund a bomb factory. In December 1929, an attempt was made to assassinate the Governor of Punjab, which wounded him in his arm.[18]\nDecline\n\nBy 1930, most of the HSRA\'s main leaders were either dead or in prison. Kailash Pati was arrested in October 1929 and turned an approver (witness for the prosecution). On 27 February 1931, Chandra Shekhar Azad shot himself in the head during a gunfight with the Allahabad Police in a famous incident of Alfred Park. Bhagat Singh, Sukhdev Thapar, and Shivaram Rajguru were hanged on 23 March 1931. After Azad\'s death, there was no central leader to unite the revolutionaries and regional differences increased. The organisation split into various regional groups and they carried out bombings and attacks on British officials in India without any central coordination. In December 1930, another attempt was made to revive the HSRA at a meeting in Meerut. However, this attempt failed with the arrests of Yashpal and Daryao Singh in 1931.[19] This effectively ended the HSRA as a united organisation though the various regional factions kept up their armed struggle until 1935.\nCriticism\n\nThe association\'s methods were diametrically opposite to that of Gandhi\'s nonviolent resistance movement. The revolutionaries and their methods were severely criticized by Gandhi. Responding to the attack on Lord Irwin\'s train, Gandhi wrote a harsh critique of the HSRA titled "The Cult of the Bomb" (Young India, 2 January 1929). In it, he declared that bomb-throwing was nothing but "froth coming to the surface in an agitated liquid". He condemned the HSRA and its actions as "cowards" and "dastardly". According to Gandhi, the HSRA\'s violent struggle had its hazards. The violence led to more reprisals and suffering. Also, it would turn inward as "it was an easy natural step" from "violence done to the foreign ruler" to "violence to our own people".[20] The HSRA responded to this criticism with its own manifesto "The Philosophy of the Bomb",[10] in which they defended their violent methods as being complementary to Gandhi\'s non-violent methods.[21]\nProminent members\nName \tInvolved in \tOutcome\nChandra Shekhar Azad \tKakori conspiracy, John P. Saunders assassination (1927) \tAbsconded in the Kakori Conspiracy Case, while living underground he re-organized the HSRA and shot himself dead in a shoot-out with police at Allahabad on 27 February 1931.[22]\nSachindra Nath Bakshi \tKakori conspiracy \tSentenced to life imprisonment in Kakori case; released in 1936 and became active in Congress but left the party after independence. He was elected as the MLA on Jan Sangh Party ticket[23]\nSuresh Chandra Bhattacharya \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case[22]\nRam Prasad Bismil \tMainpuri conspiracy (1917) and Kakori conspiracy[24] \tAbsconded in Mainpuri case; Sentenced to death in Kakori case.[citation needed] Hanged in 1926 at Gorakhpur Central Jail\nJogesh Chandra Chatterjee \tKakori conspiracy \tSentenced to life imprisonment in Kakori case; became a Member of Parliament after independence\nPranawesh Chatterjee \tKakori conspiracy \tSentenced to four years\' rigorous imprisonment in Kakori case[22]\nVishnu Sharan Dublish \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori conspiracy which was converted later into a life sentence after Naini Jail Case.[22] Joined Indian National Congress, freedom movement activities in Western Uttar Pradesh, became a member of parliament.\nManmath Nath Gupta \tKakori conspiracy \tSentenced to 14 years\' rigorous imprisonment in Kakori case; later became a journalist/writer; died in 1999 on the day of Deepavali.\nGovind Charan Kar \tKakori conspiracy \tSentenced to life in Kakori case.\nAshfaqulla Khan \tKakori conspiracy \tSentenced to death in Kakori case.[25] Hanged in 1926 at Faizabad Jail.\nPrem Krishna Khanna \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case.[22] He became a Member of Parliament from Shahjahanpur[26] in 1961 and 1966.\nRam Krishna Khatri \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case.[22]\nRajendra Nath Lahiri \tKakori conspiracy \tSentenced to death in Kakori case.[citation needed] Hanged in 1926 at Gonda Jail.\nBanwari Lal \tKakori conspiracy \tSentenced to two years\' even after being an approver in the Kakori case.[22]\nMukundi Lal \tMainpuri conspiracy (1917) and Kakori conspiracy[27] \tSentenced to seven years\' rigorous imprisonment in Mainpuri and life in Kakori conspiracy case; died in October 1981.[28]\nRam Nath Pandey \tKakori conspiracy \tSentenced to three years\' rigorous imprisonment in Kakori case.[22]\nBhupendra Nath Sanyal \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case[22]\nSachindra Nath Sanyal \tKakori conspiracy \tSentenced to life imprisonment in Andaman Cellular Jail; died of tuberculosis at Bhowali TB sanatorium in 1942.\nThakur Roshan Singh \tKakori conspiracy \tSentenced to death in Kakori case.[citation needed] Hanged in 1926 at Allahabad Jail.\nRaj Kumar Sinha \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case.[22]\nRam Dulare Trivedi \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case.[22]\nAjoy Ghosh \tLahore Conspiracy Case trial \tHe was arrested and latter imprisoned after Lahore Conspiracy Case trial in 1928 but released due to lack of evidence. Later, he joined Communist Party of India and become general secretary of CPI in 1950.\nEnd time and Dissolution\n\nAfter the death of Bhagat Singh and Chandra Shekhar Azad, another associate Udham Singh operated the HSRA from London. HSRA was dissolved in 1940 when Udham was hanged.\nLegacy\n\nA bomb factory and hideout located in Turi Bazaar, Firozpur, has been declared as a national monument by the Government of Punjab.[29]\nSee also\n\n    Sushila Didi\n    Ashfaqulla Khan\n    Delhi Conspiracy Commission\n    Naujawan Bharat Sabha\n    Revolutionary movement for Indian independence\n    Workers and Peasants Party\n\nReferences\n\nNotes\n\n    The revolutionary group from Bengal did not formally associate itself with the HSRA in 1928 but did provide Jatindra Nath Das to give advice on explosives. The Bengal group did not accept the socio-economic aspects of revolution proposed by the other groups and preferred to see it purely in terms of nationalism.[5]\n\nReferences\n\n    "To Young Political Workers". Archived from the original on 1 October 2015. Retrieved 11 March 2024.\n    "The Red Pamphlet". Archived from the original on 26 February 2024. Retrieved 26 February 2024.\n    "Ashfaqulla Khan: An epitome of Hindu-Muslim Unity and inspiration for the Youth".[permanent dead link]\n    Indian National Congress (1919). Report Of The Thirty Third Session Of The Indian National Congress. Delhi: L.M.H Press.\n    Gupta (1997)\n    Dr. Mehrotra N.C. Swatantrata Andolan Mein Shahjahanpur Ka Yogdan Page 109 & 146\n    Balinisteanu, Tudor (2012). Violence, Narrative and Myth in Joyce and Yeats: Subjective Identity and Anarcho-Syndicalist Traditions. Palgrave Macmillan. p. 60. ISBN 978-0-23029-095-2.[permanent dead link]\n    Nair (2009)\n    Sawhney (2012), p. 380\n    Bowden & Davis (2009), p. 29\n    Rana (2005a), p. 36\n    Nayar (2000), p. 39\n    Rana (2005b), p. 65\n    Grewal (2007), p. 46\n    Singh, Lala & Hooja (2007), pp. 16–18\n    Khan, 

In [30]:
# aload() function read everything as one line. It did not account for "\n" for line breaks.

In [31]:
# Either we need to split it later with additional code or we can use the sync function of load_and_split()

In [32]:
documents = loader.load_and_split()

In [33]:
documents

[Document(metadata={'source': '../assets/data/HRA.txt'}, page_content="Hindustan Socialist Republican Association\nFrom Wikipedia, the free encyclopedia\n\nHindustan Socialist Republican Association (HSRA), previously known as the Hindustan Republican Army and Hindustan Republican Association (HRA), was a left-wing Indian revolutionary organization, founded by Sachindranath Sanyal. After changes in Bhagat Singh's ideology and the influence of the Russian Revolution, they held meetings in Feroz Shah Kotla Maidan and added the word socialist to their name. Ram Prasad Bismil, Ashfaqulla Khan, Sachindra Nath Bakshi, Sachindranath Sanyal and Jogesh Chandra Chatterjee were the leaders of the group at the time. HSRA's manifesto titled The Revolutionary and written constitution were produced as evidence in the Kakori conspiracy case of 1925. \n\nOrigins\nBackground\nThe non-cooperation movement of 1919 had led to a large-scale mobilization of the Indian population against the British Raj. Although intended as a non-violent resistance movement, due to heightened tensions, and a brutal response by the British police forces, it had soon become violent. After the Chauri Chaura incident, where several police officers were locked in a police station, which was subsequently set on fire by demonstrators, Mahatma Gandhi suspended the movement to prevent the escalation of violence. This disillusioned a section of nationalists who felt the suspension was premature and unwarranted. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the 37th session of the Indian National Congress, held in Gaya, Bihar.[4] The political vacuum created by the suspension led to the formation of revolutionary movements by the more radical amongst those who sought to overthrow British Raj.\n\nOpposition of Gandhi in Gaya Congress\nIn February 1922, some agitating farmers were killed in Chauri Chaura by the police. Consequently, the police station of Chauri Chaura was attacked by the people and 22 policemen were burnt alive. \nWithout ascertaining the facts behind this incident, Mahatma Gandhi, declared an immediate stop to the Non-cooperation movement (he himself had given a call for it) without consulting any executive committee member of the Congress. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the Gaya Congress of 1922. When Gandhi refused to rescind his decision, the Indian National Congress was divided into two groups – one liberal and the other for rebellion. In January 1923, the liberal group formed a new Swaraj Party under the joint leadership of Moti Lal Nehru and Chittaranjan Das, and the youth group formed a revolutionary party under the leadership of Bismil.\nYellow Paper constitution\n\nWith the consent of Lala Har Dayal, Bismil went to Allahabad where he drafted the constitution of the party in 1923 with the help of Sachindra Nath Sanyal and another revolutionary of Bengal, Dr. Jadugopal Mukherjee.[6][full citation needed] The basic name and aims of the organisation were typed on a Yellow Paper and later on a subsequent Constitutional Committee Meeting was conducted on 3 October 1924 at Cawnpore in the United Provinces under Sanyal's chairmanship.\nSharing responsibility\n\nThis meeting decided the name of the party would be the Hindustan Republican Association (HRA). Bismil was declared the District Organiser for Shahjahanpur and chief of arms division, as well as provincial organiser of United Provinces. Sachindra Nath Sanyal became National Organiser and another senior member, Jogesh Chandra Chatterjee, was Coordinator of the Anushilan Samiti. After attending the meeting in Cawnpore, both Sanyal and Chatterjee left the United Province and proceeded to Bengal for further extension of the organisation.[citation needed]"),
 Document(metadata={'source': '../assets/data/HRA.txt'}, page_content='The HRA established branches in Agra, Allahabad, Benares, Cawnpore, Lucknow, Saharanpur and Shahjahanpur. They also manufactured bombs in Calcutta – at Dakshineswar and Shovabazar and at Deoghar in Jharkhand (then Bihar province). The Calcutta workshops were discovered by the police in 1925 and those in Deoghar were found in 1927.[5]\nPublication of Revolutionary\n\nSanyal wrote a manifesto for the HRA entitled Revolutionary. This was distributed around large cities of North India on 1 January 1925.[7] It proposed the overthrow of British colonial rule and its replacement with what it termed a Federal Republic of the United States of India. In addition, it sought universal suffrage and the socialist-oriented aim of the abolition of "all systems which make any kind of exploitation of man by man possible"[5]\n\nThe policies of Gandhi were criticised and youths were called to join the organisation. The police were astonished to see the language used and sought its leader in Bengal. Sanyal had gone to despatch this pamphlet in bulk and was arrested in Bankura, West Bengal. Before Sanyal\'s arrest, Jogesh Chandra Chatterjee had also been caught by police at Howrah railway station of Calcutta, Bengal Presidency.\nEarly activities\nWall painting of Bhagat Singh; Rewalsar, India, 2009\n\nThere were many early attempts at disruption and obtaining funds, such as the robbery of the houses of a village officials at Dwarikapur and Bichpuri in 1922–23, but the Kakori train robbery was the most prominent of the early HRA efforts. The Kakori event occurred on 9 August 1925, when HRA members looted government money from a train around 10 miles (16 km) from Lucknow and accidentally killed a passenger in the process. Significant members of the HRA were arrested and tried for their involvement in that incident and others which had preceded it. The outcome was that four leaders – Ashfaqullah Khan, Ram Prasad Bismil, Roshan Singh and Rajendra Lahiri – were hanged in December 1927 and a further 16 imprisoned for lengthy terms. The result of the trial, in which the HRA participants sang patriotic songs and displayed other forms of defiance, seriously damaged the leadership of the HRA and dealt a major blow to its activities. Many associated with the HRA who escaped trial found themselves placed under surveillance or detained for various reasons. Chandra Shekhar Azad was the only one of the principal leaders who managed to escape arrest whereas Banwari Lal became an approver.[5]\nMajor activities\n\nIn 1928, the British government set up the Commission, headed by Sir John Simon, to report on the political situation in India. Some Indian activist groups protested the commission, because it did not include a single Indian in its membership, although by no means all did so. The effect was to unite various activist factions in opposition.[8]'),
 Document(metadata={'source': '../assets/data/HRA.txt'}, page_content='Responding to the rise in anti-colonial sentiment in 1928,[8] the HRA became the Hindustan Socialist Republican Association, with the change of name probably being largely due to the influence of Bhagat Singh.[9] Around the time of the Kakori robbery and the subsequent trial, various revolutionary groups had emerged in places such as Bengal, Bihar, and Punjab. These groups and the HRA met at Feroz Shah Kotla, in Delhi, on 8–9 September 1928, and from this emerged the HSRA.[a] The socialist leanings voiced in the earlier HRA manifesto had gradually moved more towards Marxism and the HSRA spoke of a revolution involving a struggle by the masses to establish "the dictatorship of the proletariat" and the banishment of "parasites from the seat of political power". It saw itself as being at the forefront of this revolution, spreading the word and acting as the armed section of the masses. Its ideals were apparent in other movements elsewhere at that time, including incidents of communist-inspired industrial action by workers and the rural kisan movement.[5] At the request of Bhagat Singh, the newly named HSRA resolved to bomb members of the Simon Commission and also to cease robbing rich people, the latter being a realisation that the Kakori conspirators had suffered most from the evidence given by such people.[8] At that time the HRA was being transformed into the HSRA and it was decided that the new organization would work in cooperation with the Communist International.\n\nThe HSRA\'s manifesto titled Philosophy of the Bomb was written by Bhagwati Charan Vohra.[10]\nKilling of John P. Saunders\n\nWhen the Simon Commission visited Lahore on 30 October 1928, Lala Lajpat Rai led a peaceful protest against the commission. The police responded with violence, with the Superintendent of Police, James A. Scott, ordering his men to lathi charge the protesters. Rai was beaten but addressed a meeting later. He died on 17 November 1928, perhaps in part because of his injuries although this is uncertain. Historian Neeti Nair says "His death was widely attributed to the mental if not physical shock he had suffered."[8] When the matter of Lala Lajpat Rai\'s death was raised in the British Parliament, the government denied any causal role.[11] Bhagat Singh vowed to take revenge,[11] and joined other revolutionaries, Shivaram Rajguru, Jai Gopal, Sukhdev Thapar and Chandra Shekhar Azad, in a plot to kill Scott.[5] However, in a case of mistaken identity, Singh was signalled to shoot on the appearance of John P. Saunders, an Assistant superintendent. He was shot by Rajguru and Singh while leaving the District Police Headquarters in Lahore on 17 December 1928.[12] Chanan Singh, a Head Constable who was chasing them, was killed by Azad\'s covering fire.[13]\n\nThis case of mistaken identity did not stop Singh and his fellow-members of the HSRA from claiming that retribution had been exacted.[5] The next day the HSRA acknowledged the assassination by putting up posters in Lahore that read\n\n    J. P. Saunders is dead; Lala Lajpat Rai is avenged. ... In this man has died an agent of the British authority in India. ... Sorry for the bloodshed of the human being, but the sacrifice of individuals at the altar of revolution ... is inevitable.[14]\n\nFront page of the Tribune (25 March 1931) published from Lahore, reporting the execution of Singh, Sukhdev & Rajguru\n\nThe perpetrators of the Saunders murder having eluded capture and gone into hiding, the next major action by the HSRA was the bombing of the Central Legislative Assembly in Delhi on 8 April 1929. This was a provocative propaganda exercise, intended to highlight the aims of the HSRA and timed as a protest against the introduction of the Public Safety Bill and the Trade Disputes Bill, both of which had been drafted in an attempt to counter the effects of communist activities and trade unionism[5][15]'),
 Document(metadata={'source': '../assets/data/HRA.txt'}, page_content='Singh and Batukeshwar Dutt threw bombs at the empty benches, being careful to ensure that there were no casualties in order to highlight the propagandist nature of their action. They made no attempt to escape and courted arrest while shouting Inquilab Zindabad (Long Live the Revolution), Vande Mataram (Hail to motherland) and Samrajyavad Murdabad\' (Down with Imperialism). Their rationale for the bombing was explained in a leaflet titled "To Make the Deaf Hear" (paraphrasing the words of Édouard Vaillant). This leaflet was also thrown in the assembly and was reproduced the next day in the Hindustan Times. On 15 April 1929, police raided the HSRA\'s bomb factory in Lahore and arrested Kishori Lal, Sukhdev and Jai Gopal. The Assembly Bomb case and the Saunders murder case trial followed and Singh, Sukhdev and Rajguru were hanged on 23 March 1931 for their actions.[5][15]\nLater activities\n\nIn December 1929, the HSRA bombed the special train of Lord Irwin. The Viceroy escaped unhurt. Later, the Lahore faction of HSRA broke away and formed the Atishi Chakar (The Ring of Fire) party under the leadership of Hans Raj Vohra. They carried out a series of bombings across Punjab in June 1929. On 21 January 1929, Bhagat Singh and his fellow comrades were accused in the Lahore Conspiracy Case, appeared in the court wearing red scarves. As soon as the magistrate took his chair, they raised slogans "Long Live Socialist Revolution", "Long Live Communist International", "Long Live People" "Lenin\'s Name Will Never Die", and "Down with Imperialism".[16][17] On 1 September 1929, the Rawalpindi faction made a failed attempt to burgle the Office of the Controller of Military Accounts. During this period the leading members of the HSRA were Chandra Shekhar Azad, Yashpal, Bhagwati Charan Vohra and Kailash Pati. In July 1929, the HSRA robbed the Gadodia stores in New Delhi and carried away 14,000 rupees. This money was later used to fund a bomb factory. In December 1929, an attempt was made to assassinate the Governor of Punjab, which wounded him in his arm.[18]\nDecline\n\nBy 1930, most of the HSRA\'s main leaders were either dead or in prison. Kailash Pati was arrested in October 1929 and turned an approver (witness for the prosecution). On 27 February 1931, Chandra Shekhar Azad shot himself in the head during a gunfight with the Allahabad Police in a famous incident of Alfred Park. Bhagat Singh, Sukhdev Thapar, and Shivaram Rajguru were hanged on 23 March 1931. After Azad\'s death, there was no central leader to unite the revolutionaries and regional differences increased. The organisation split into various regional groups and they carried out bombings and attacks on British officials in India without any central coordination. In December 1930, another attempt was made to revive the HSRA at a meeting in Meerut. However, this attempt failed with the arrests of Yashpal and Daryao Singh in 1931.[19] This effectively ended the HSRA as a united organisation though the various regional factions kept up their armed struggle until 1935.\nCriticism'),
 Document(metadata={'source': '../assets/data/HRA.txt'}, page_content='The association\'s methods were diametrically opposite to that of Gandhi\'s nonviolent resistance movement. The revolutionaries and their methods were severely criticized by Gandhi. Responding to the attack on Lord Irwin\'s train, Gandhi wrote a harsh critique of the HSRA titled "The Cult of the Bomb" (Young India, 2 January 1929). In it, he declared that bomb-throwing was nothing but "froth coming to the surface in an agitated liquid". He condemned the HSRA and its actions as "cowards" and "dastardly". According to Gandhi, the HSRA\'s violent struggle had its hazards. The violence led to more reprisals and suffering. Also, it would turn inward as "it was an easy natural step" from "violence done to the foreign ruler" to "violence to our own people".[20] The HSRA responded to this criticism with its own manifesto "The Philosophy of the Bomb",[10] in which they defended their violent methods as being complementary to Gandhi\'s non-violent methods.[21]\nProminent members\nName \tInvolved in \tOutcome\nChandra Shekhar Azad \tKakori conspiracy, John P. Saunders assassination (1927) \tAbsconded in the Kakori Conspiracy Case, while living underground he re-organized the HSRA and shot himself dead in a shoot-out with police at Allahabad on 27 February 1931.[22]\nSachindra Nath Bakshi \tKakori conspiracy \tSentenced to life imprisonment in Kakori case; released in 1936 and became active in Congress but left the party after independence. He was elected as the MLA on Jan Sangh Party ticket[23]\nSuresh Chandra Bhattacharya \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case[22]\nRam Prasad Bismil \tMainpuri conspiracy (1917) and Kakori conspiracy[24] \tAbsconded in Mainpuri case; Sentenced to death in Kakori case.[citation needed] Hanged in 1926 at Gorakhpur Central Jail\nJogesh Chandra Chatterjee \tKakori conspiracy \tSentenced to life imprisonment in Kakori case; became a Member of Parliament after independence\nPranawesh Chatterjee \tKakori conspiracy \tSentenced to four years\' rigorous imprisonment in Kakori case[22]\nVishnu Sharan Dublish \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori conspiracy which was converted later into a life sentence after Naini Jail Case.[22] Joined Indian National Congress, freedom movement activities in Western Uttar Pradesh, became a member of parliament.\nManmath Nath Gupta \tKakori conspiracy \tSentenced to 14 years\' rigorous imprisonment in Kakori case; later became a journalist/writer; died in 1999 on the day of Deepavali.\nGovind Charan Kar \tKakori conspiracy \tSentenced to life in Kakori case.\nAshfaqulla Khan \tKakori conspiracy \tSentenced to death in Kakori case.[25] Hanged in 1926 at Faizabad Jail.\nPrem Krishna Khanna \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case.[22] He became a Member of Parliament from Shahjahanpur[26] in 1961 and 1966.\nRam Krishna Khatri \tKakori conspiracy \tSentenced to ten years\' rigorous imprisonment in Kakori case.[22]\nRajendra Nath Lahiri \tKakori conspiracy \tSentenced to death in Kakori case.[citation needed] Hanged in 1926 at Gonda Jail.\nBanwari Lal \tKakori conspiracy \tSentenced to two years\' even after being an approver in the Kakori case.[22]\nMukundi Lal \tMainpuri conspiracy (1917) and Kakori conspiracy[27] \tSentenced to seven years\' rigorous imprisonment in Mainpuri and life in Kakori conspiracy case; died in October 1981.[28]\nRam Nath Pandey \tKakori conspiracy \tSentenced to three years\' rigorous imprisonment in Kakori case.[22]\nBhupendra Nath Sanyal \tKakori conspiracy \tSentenced to five years\' rigorous imprisonment in Kakori case[22]\nSachindra Nath Sanyal \tKakori conspiracy \tSentenced to life imprisonment in Andaman Cellular Jail; died of tuberculosis at Bhowali TB sanatorium in 1942.\nThakur Roshan Singh \tKakori conspiracy \tSentenced to death in Kakori case.[citation needed] Hanged in 1926 at Allahabad Jail.'),
 Document(metadata={'source': '../assets/data/HRA.txt'}, page_content="Thakur Roshan Singh \tKakori conspiracy \tSentenced to death in Kakori case.[citation needed] Hanged in 1926 at Allahabad Jail.\nRaj Kumar Sinha \tKakori conspiracy \tSentenced to ten years' rigorous imprisonment in Kakori case.[22]\nRam Dulare Trivedi \tKakori conspiracy \tSentenced to five years' rigorous imprisonment in Kakori case.[22]\nAjoy Ghosh \tLahore Conspiracy Case trial \tHe was arrested and latter imprisoned after Lahore Conspiracy Case trial in 1928 but released due to lack of evidence. Later, he joined Communist Party of India and become general secretary of CPI in 1950.\nEnd time and Dissolution"),

In [34]:
# We can also read text file using conventional methods and split it based on some logics.
# For example :

documents = []
with open(file=data_directory+"HRA.txt",mode="r") as f:
    for line in f:
        # print(f.readline())
        documents.append(f.readline())

In [35]:
print(documents); print(len(documents))

['From Wikipedia, the free encyclopedia\n', "Hindustan Socialist Republican Association (HSRA), previously known as the Hindustan Republican Army and Hindustan Republican Association (HRA), was a left-wing Indian revolutionary organization, founded by Sachindranath Sanyal. After changes in Bhagat Singh's ideology and the influence of the Russian Revolution, they held meetings in Feroz Shah Kotla Maidan and added the word socialist to their name. Ram Prasad Bismil, Ashfaqulla Khan, Sachindra Nath Bakshi, Sachindranath Sanyal and Jogesh Chandra Chatterjee were the leaders of the group at the time. HSRA's manifesto titled The Revolutionary and written constitution were produced as evidence in the Kakori conspiracy case of 1925. \n", 'Origins\n', 'The non-cooperation movement of 1919 had led to a large-scale mobilization of the Indian population against the British Raj. Although intended as a non-violent resistance movement, due to heightened tensions, and a brutal response by the British police forces, it had soon become violent. After the Chauri Chaura incident, where several police officers were locked in a police station, which was subsequently set on fire by demonstrators, Mahatma Gandhi suspended the movement to prevent the escalation of violence. This disillusioned a section of nationalists who felt the suspension was premature and unwarranted. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the 37th session of the Indian National Congress, held in Gaya, Bihar.[4] The political vacuum created by the suspension led to the formation of revolutionary movements by the more radical amongst those who sought to overthrow British Raj.\n', 'Opposition of Gandhi in Gaya Congress\n', 'Without ascertaining the facts behind this incident, Mahatma Gandhi, declared an immediate stop to the Non-cooperation movement (he himself had given a call for it) without consulting any executive committee member of the Congress. Ram Prasad Bismil and his group of youth strongly opposed Gandhi in the Gaya Congress of 1922. When Gandhi refused to rescind his decision, the Indian National Congress was divided into two groups – one liberal and the other for rebellion. In January 1923, the liberal group formed a new Swaraj Party under the joint leadership of Moti Lal Nehru and Chittaranjan Das, and the youth group formed a revolutionary party under the leadership of Bismil.\n', '\n', 'Sharing responsibility\n', 'This meeting decided the name of the party would be the Hindustan Republican Association (HRA). Bismil was declared the District Organiser for Shahjahanpur and chief of arms division, as well as provincial organiser of United Provinces. Sachindra Nath Sanyal became National Organiser and another senior member, Jogesh Chandra Chatterjee, was Coordinator of the Anushilan Samiti. After attending the meeting in Cawnpore, both Sanyal and Chatterjee left the United Province and proceeded to Bengal for further extension of the organisation.[citation needed]\n', 'The HRA established branches in Agra, Allahabad, Benares, Cawnpore, Lucknow, Saharanpur and Shahjahanpur. They also manufactured bombs in Calcutta – at Dakshineswar and Shovabazar and at Deoghar in Jharkhand (then Bihar province). The Calcutta workshops were discovered by the police in 1925 and those in Deoghar were found in 1927.[5]\n', '\n', '\n', 'Early activities\n', '\n', 'Major activities\n', 'In 1928, the British government set up the Commission, headed by Sir John Simon, to report on the political situation in India. Some Indian activist groups protested the commission, because it did not include a single Indian in its membership, although by no means all did so. The effect was to unite various activist factions in opposition.[8]\n', 'Responding to the rise in anti-colonial sentiment in 1928,[8] the HRA became the Hindustan Socialist Republican Association, with the change of name probably being largely due to the influence of Bhagat Singh.[9] Around the time of the Kakori robbery and the subsequent trial, various revolutionary groups had emerged in places such as Bengal, Bihar, and Punjab. These groups and the HRA met at Feroz Shah Kotla, in Delhi, on 8–9 September 1928, and from this emerged the HSRA.[a] The socialist leanings voiced in the earlier HRA manifesto had gradually moved more towards Marxism and the HSRA spoke of a revolution involving a struggle by the masses to establish "the dictatorship of the proletariat" and the banishment of "parasites from the seat of political power". It saw itself as being at the forefront of this revolution, spreading the word and acting as the armed section of the masses. Its ideals were apparent in other movements elsewhere at that time, including incidents of communist-inspired industrial action by workers and the rural kisan movement.[5] At the request of Bhagat Singh, the newly named HSRA resolved to bomb members of the Simon Commission and also to cease robbing rich people, the latter being a realisation that the Kakori conspirators had suffered most from the evidence given by such people.[8] At that time the HRA was being transformed into the HSRA and it was decided that the new organization would work in cooperation with the Communist International.\n', "The HSRA's manifesto titled Philosophy of the Bomb was written by Bhagwati Charan Vohra.[10]\n", '\n', '\n', '\n', '\n', '\n', '\n', 'Later activities\n', 'In December 1929, the HSRA bombed the special train of Lord Irwin. The Viceroy escaped unhurt. Later, the Lahore faction of HSRA broke away and formed the Atishi Chakar (The Ring of Fire) party under the leadership of Hans Raj Vohra. They carried out a series of bombings across Punjab in June 1929. On 21 January 1929, Bhagat Singh and his fellow comrades were accused in the Lahore Conspiracy Case, appeared in the court wearing red scarves. As soon as the magistrate took his chair, they raised slogans "Long Live Socialist Revolution", "Long Live Communist International", "Long Live People" "Lenin\'s Name Will Never Die", and "Down with Imperialism".[16][17] On 1 September 1929, the Rawalpindi faction made a failed attempt to burgle the Office of the Controller of Military Accounts. During this period the leading members of the HSRA were Chandra Shekhar Azad, Yashpal, Bhagwati Charan Vohra and Kailash Pati. In July 1929, the HSRA robbed the Gadodia stores in New Delhi and carried away 14,000 rupees. This money was later used to fund a bomb factory. In December 1929, an attempt was made to assassinate the Governor of Punjab, which wounded him in his arm.[18]\n', '\n', 'Criticism\n', 'The association\'s methods were diametrically opposite to that of Gandhi\'s nonviolent resistance movement. The revolutionaries and their methods were severely criticized by Gandhi. Responding to the attack on Lord Irwin\'s train, Gandhi wrote a harsh critique of the HSRA titled "The Cult of the Bomb" (Young India, 2 January 1929). In it, he declared that bomb-throwing was nothing but "froth coming to the surface in an agitated liquid". He condemned the HSRA and its actions as "cowards" and "dastardly". According to Gandhi, the HSRA\'s violent struggle had its hazards. The violence led to more reprisals and suffering. Also, it would turn inward as "it was an easy natural step" from "violence done to the foreign ruler" to "violence to our own people".[20] The HSRA responded to this criticism with its own manifesto "The Philosophy of the Bomb",[10] in which they defended their violent methods as being complementary to Gandhi\'s non-violent methods.[21]\n', 'Name \tInvolved in \tOutcome\n', 'Sachindra Nath Bakshi \tKakori conspiracy \tSentenced to life imprisonment in Kakori case; released in 1936 and became active in Congress but left the party after independence. He was elected as the MLA on Jan Sangh Party ticket[23]\n', 'Ram Prasad Bismil \tMainpuri conspiracy (1917) and Kakori conspiracy[24] \tAbsconded in Mainpuri case; Sentenced to death in Kakori case.[citation needed] Hanged in 1926 at Gorakhpur Central Jail\n', "Pranawesh Chatterjee \tKakori conspiracy \tSentenced to four years' rigorous imprisonment in Kakori case[22]\n", "Manmath Nath Gupta \tKakori conspiracy \tSentenced to 14 years' rigorous imprisonment in Kakori case; later became a journalist/writer; died in 1999 on the day of Deepavali.\n", 'Ashfaqulla Khan \tKakori conspiracy \tSentenced to death in Kakori case.[25] Hanged in 1926 at Faizabad Jail.\n', "Ram Krishna Khatri \tKakori conspiracy \tSentenced to ten years' rigorous imprisonment in Kakori case.[22]\n", "Banwari Lal \tKakori conspiracy \tSentenced to two years' even after being an approver in the Kakori case.[22]\n", "Ram Nath Pandey \tKakori conspiracy \tSentenced to three years' rigorous imprisonment in Kakori case.[22]\n", 'Sachindra Nath Sanyal \tKakori conspiracy \tSentenced to life imprisonment in Andaman Cellular Jail; died of tuberculosis at Bhowali TB sanatorium in 1942.\n', "Raj Kumar Sinha \tKakori conspiracy \tSentenced to ten years' rigorous imprisonment in Kakori case.[22]\n", 'Ajoy Ghosh \tLahore Conspiracy Case trial \tHe was arrested and latter imprisoned after Lahore Conspiracy Case trial in 1928 but released due to lack of evidence. Later, he joined Communist Party of India and become general secretary of CPI in 1950.\n', '\n', 'Legacy\n', 'A bomb factory and hideout located in Turi Bazaar, Firozpur, has been declared as a national monument by the Government of Punjab.[29]\n', '\n', '    Ashfaqulla Khan\n', '    Naujawan Bharat Sabha\n', '    Workers and Peasants Party\n', 'References\n', 'Notes\n', '    The revolutionary group from Bengal did not formally associate itself with the HSRA in 1928 but did provide Jatindra Nath Das to give advice on explosives. The Bengal group did not accept the socio-economic aspects of revolution proposed by the other groups and preferred to see it purely in terms of nationalism.[5]\n', 'References\n', '    "To Young Political Workers". Archived from the original on 1 October 2015. Retrieved 11 March 2024.\n', '    "Ashfaqulla Khan: An epitome of Hindu-Muslim Unity and inspiration for the Youth".[permanent dead link]\n', '    Gupta (1997)\n', '    Balinisteanu, Tudor (2012). Violence, Narrative and Myth in Joyce and Yeats: Subjective Identity and Anarcho-Syndicalist Traditions. Palgrave Macmillan. p. 60. ISBN 978-0-23029-095-2.[permanent dead link]\n', '    Sawhney (2012), p. 380\n', '    Rana (2005a), p. 36\n', '    Rana (2005b), p. 65\n', '    Singh, Lala & Hooja (2007), pp. 16–18\n', '    "How Russian Revolution Inspired Undivided India\'s Literary, Political Figures". me NewsClick. Archived from the original on 8 November 2019. Retrieved 7 November 2018.\n', '    Ralhan (1998), pp. 720–730\n', '    Nayar (2000), pp. 173–175\n', '    Mahaur (1978), p. 84\n', '    "NAUJAWAN BHARAT SABHA & HSRA" (PDF). Archived (PDF) from the original on 14 June 2020. Retrieved 8 January 2020.\n', '    Mahaur (1978), p. 65\n', '    "Revolutionaries\' hideout at Ferozepur declared protected, Punjab govt tells HC". The Times of India. Archived from the original on 4 September 2018. Retrieved 23 August 2018.\n', 'Bibliography\n', '    Amstutz, Andrew. "Review essay: Alternative histories of revolutionaries in modern South Asia: context, chronology, and archives." India Review 18.3 (2019): 324–342. online[dead link]\n', '    Gandhi, Rajmohan (2008), Gandhi: the man, his people, and the empire, Berkeley: University of California Press, ISBN 978-0-520-25570-8\n', '    Gupta, Amit Kumar (1997), "Defying Death: Nationalist Revolutionism in India, 1897–1938", Social Scientist, 25 (9/10): 3–27, doi:10.2307/3517678, JSTOR 3517678 (subscription required)\n', '    Maclean, Kama. A Revolutionary History of Interwar India: Violence Image, Voice and Text (London, 2015) focus on the Hindustan Socialist Republican Army.\n', '    Nair, Neeti (May 2009), "Bhagat Singh as \'Satyagrahi\': The Limits to Non-violence in Late Colonial India", Modern Asian Studies, 43 (3), Cambridge University Press: 649–681, doi:10.1017/s0026749x08003491, JSTOR 20488099, S2CID 143725577\n', '    Ralhan, Om Prakash (1998), Encyclopaedia of political parties, Volumes 33-50, New Delhi: Anmol Publications, ISBN 81-7488-865-9 [clarification needed]\n', '    Rana, Bhawan Singh (2005a), Bhagat Singh, Diamond Pocket Books, ISBN 978-81-288-0827-2\n', '    Singh, Bhagat; Lala, Chaman; Hooja, Bhupendra (2007), The jail notebook and other writings, New Delhi: Left Word Books, ISBN 978-81-87496-72-4\n', 'Further reading\n', '    Govind, Nikhil (2014). Between Love and Freedom: The Revolutionary in the Hindi Novel. Routledge. ISBN 978-1-31755-976-4.\n']
78

In [36]:
# Load : 
# 
# pdf file containing only text :
# Download file from : https://s21.q4cdn.com/399680738/files/doc_financials/2025/q2/META-Q2-2025-Earnings-Call-Transcript.pdf

In [37]:
filename = "META-Q2-2025-Earnings-Call-Transcript.pdf"

In [38]:
# For reading PDFs, there are many options available; and all of them have their own features because PDFs can go complex.
# We will also see those difficult scenarios. This notebook may get long due to extraction itself.

In [39]:
from langchain_community.document_loaders import PyMuPDFLoader

In [40]:
loader = PyMuPDFLoader(
    file_path=data_directory+filename
)

In [41]:
documents = loader.load_and_split()

In [42]:
print(len(documents));documents

19

[Document(metadata={'producer': 'Microsoft® Word for Microsoft 365', 'creator': 'Microsoft® Word for Microsoft 365', 'creationdate': '2025-07-30T21:31:06-04:00', 'source': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'file_path': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'total_pages': 19, 'format': 'PDF 1.7', 'title': 'META Q2 2025 Earnings Call Transcript', 'author': 'Kenneth Dorell;Jonathan Rong Li', 'subject': '', 'keywords': '', 'moddate': '2025-07-30T21:31:06-04:00', 'trapped': '', 'modDate': "D:20250730213106-04'00'", 'creationDate': "D:20250730213106-04'00'", 'page': 0}, page_content="1 \n \nMeta Platforms, Inc. (META) \nSecond Quarter 2025 Results Conference Call \nJuly 30th, 2025 \n \nKenneth Dorell, Director, Investor Relations \n \nThank you. Good afternoon and welcome to Meta’s second quarter 2025 earnings conference call.  \nJoining me today are Mark Zuckerberg, CEO and Susan Li, CFO.  \n \nOur remarks today will include forward‐looking statements, which are based on assumptions as of \ntoday. Actual results may differ materially as a result of various factors including those set forth in \ntoday’s earnings press release, and in our quarterly report on Form 10-Q filed with the SEC. We \nundertake no obligation to update any forward-looking statement.  \n \nDuring this call we will present both GAAP and certain non‐GAAP financial measures.  A \nreconciliation of GAAP to non‐GAAP measures is included in today’s earnings press release. The \nearnings press release and an accompanying investor presentation are available on our website at \ninvestor.atmeta.com. \n \nAnd now, I’d like to turn the call over to Mark. \n \nMark Zuckerberg, CEO \n \nThanks Ken -- thanks everyone for joining today. \n \nWe had another strong quarter with more than 3.4 billion people using at least one of our apps \neach day -- and strong engagement across the board. Our business continues to perform very \nwell, which enables us to invest heavily in our AI efforts. \n \nOver the last few months we have begun to see glimpses of our AI systems improving themselves. \nThe improvement is slow for now, but undeniable. Developing superintelligence -- which we define \nas AI that surpasses human intelligence in every way -- we think is now in sight. \n \nMeta's vision is to bring personal superintelligence to everyone -- so that people can direct it \ntowards what they value in their own lives. We believe this has the potential to begin an exciting \nnew era of individual empowerment. \n \nA lot has been written about the economic and scientific advances that superintelligence can \nbring. I am extremely optimistic about this. But I think that if history is a guide, then an even more \nimportant role will be how superintelligence empowers people to be more creative, develop \nculture and communities, connect with each other, and lead more fulfilling lives. \n \nTo build this future, we've established Meta Superintelligence Labs, which includes our \nfoundations, product, and FAIR teams, as well as a new lab that is focused on developing the next \ngeneration of our models. We're making good progress towards Llama 4.1 and 4.2 -- and in \nparallel, we're also working on our next generation of models that will push the frontier in the next \nyear or so. \n \nWe're building an elite, talent-dense team. Alexandr Wang is leading the overall team, Nat \nFriedman is leading our AI products and applied research, and Shengjia Zhao is Chief Scientist for"),
 Document(metadata={'producer': 'Microsoft® Word for Microsoft 365', 'creator': 'Microsoft® Word for Microsoft 365', 'creationdate': '2025-07-30T21:31:06-04:00', 'source': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'file_path': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'total_pages': 19, 'format': 'PDF 1.7', 'title': 'META Q2 2025 Earnings Call Transcript', 'author': 'Kenneth Dorell;Jonathan Rong Li', 'subject': '', 'keywords': '', 'moddate': '2025-07-30T21:31:06-04:00', 'trapped': '', 'modDate': "D:20250730213106-04'00'", 'creationDate': "D:20250730213106-04'00'", 'page': 1}, page_content="2 \n \nthe new effort. They're all incredibly talented leaders and I'm excited to work closely with them \nand the world-class group of AI researchers, and infrastructure and data engineers that we're \nassembling. \n \nI've spent a lot of time building this team this quarter, and the reason that so many people are \nexcited to join is because Meta has all the ingredients required to build leading models and deliver \nthem to billions of people. The people who are joining us will have access to unparalleled compute \nas we build out several multi-GW clusters. Our Prometheus cluster is coming online next year and \nwe think it'll be the world's first 1GW+ cluster. We're also building out Hyperion, which will be able \nto scale up to 5GW over several years. And we have multiple more titan clusters in development as \nwell. \n \nWe're making all these investments because we have conviction that superintelligence is going to \nimprove every aspect of what we do. \n \nFrom a business perspective, I mentioned last quarter that there are five basic opportunities that \nwe're pursuing: improved advertising, more engaging experiences, business messaging, Meta AI, \nand AI devices. So I can go into a bit of detail on each. \n \nOn advertising, the strong performance this quarter is largely thanks to AI unlocking greater \nefficiency and gains across our ads system. This quarter, we expanded our new AI-powered \nrecommendation model for ads to new surfaces and improved its performance by using more \nsignals and a longer context. It's driven roughly 5% more ad conversions on Instagram and 3% on \nFacebook. \n \nWe're also seeing good progress with AI for ad creative -- with a meaningful percent of our ad \nrevenue now coming from campaigns using one of our Generative AI features. This is going to be \nespecially valuable for smaller advertisers with limited budgets, while agencies will continue the \nimportant work to help larger brands apply these tools strategically. \n \nThe second opportunity is more engaging experiences. AI is significantly improving our ability to \nshow people content that they’re going to find interesting and useful. Advancements in our \nrecommendation systems have improved quality so much that it has led to a 5% increase in time \nspent on Facebook and 6% on Instagram just this quarter. \n \nThere's a lot of potential for content itself to get better too. We're seeing early progress with the \nlaunch of our AI video editing tools across Meta AI and our new Edits app, and there's a lot more to \ndo here. \n \nThe third opportunity is business messaging. I've talked before about how I believe every business \nwill soon have a business AI just like they have an email address, social media account, and \nwebsite. We're starting to see some product market fit in a number of countries where we're \ntesting these agents, and we're integrating these business AIs into ads on Facebook and \nInstagram, as well as directly into e-commerce websites. \n \nThe fourth opportunity is Meta AI. Its reach is already quite impressive with more than a billion \nmonthly actives. Our focus is now deepening the experience and making Meta AI the leading \npersonal AI. As we continue improving our models we see engagement grow, so our next \ngeneration of models is going to continue to really help here."),
 Document(metadata={'producer': 'Microsoft® Word for Microsoft 365', 'creator': 'Microsoft® Word for Microsoft 365', 'creationdate': '2025-07-30T21:31:06-04:00', 'source': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'file_path': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'total_pages': 19, 'format': 'PDF 1.7', 'title': 'META Q2 2025 Earnings Call Transcript', 'author': 'Kenneth Dorell;Jonathan Rong Li', 'subject': '', 'keywords': '', 'moddate': '2025-07-30T21:31:06-04:00', 'trapped': '', 'modDate': "D:20250730213106-04'00'", 'creationDate': "D:20250730213106-04'00'", 'page': 2}, page_content="3 \n \nThe fifth opportunity is AI devices. We continue to see strong momentum with our Ray-Ban Meta \nglasses, with sales accelerating. We're also launching new performance AI glasses with the Oakley \nMeta HSTNs. They have longer battery life, higher resolution camera, and are designed for sports. \nThe percent of people using Meta AI is growing and we're seeing new users' AI retention increase \ntoo, which is a good sign for that continued use. I think that AI glasses are going to be the main \nway that we integrate superintelligence into our day-to-day lives, so it's important to have all \nthese different styles that appeal to different people in different settings. \n \nFinally, we’re seeing people continue to spend more time with our Quest ecosystem and the \ncommunity continues to grow steadily. We launched the Meta Quest 3S Xbox Edition last month, \nand we're seeing record interest in cloud gaming. And beyond gaming, we continue to see a \nbroader set of use cases with media and web-browsing contributing a significant portion of \nengagement. \n \nWe’re going to have more to share on all of this, especially our Reality Labs work, at Connect on \nSeptember 17th, so I encourage you to tune into that. \n \nOverall, this has been a busy quarter. Strong business performance and real momentum in \nassembling both the talent and the compute needed to build personal superintelligence for \neveryone. I am very grateful for our teams who are working hard to deliver this, and thanks to all of \nyou for being on this journey with us. And now, here's Susan. \n \nSusan Li, CFO \n \nThanks Mark and good afternoon everyone.  \n \nLet’s begin with our consolidated results. All comparisons are on a year-over-year basis unless \notherwise noted. \n \nQ2 total revenue was $47.5 billion, up 22% on both a reported and constant currency basis. \n \nQ2 total expenses were $27.1 billion, up 12% compared to last year. \n \nIn terms of the specific line items: \n \nCost of revenue increased 16%, driven mostly by higher infrastructure costs and payments to \npartners, partially offset by a benefit from the previously announced extension of server useful \nlives.  \n \nR&D increased 23%, mostly due to higher employee compensation and infrastructure costs. \n \nMarketing & Sales increased 9%, primarily due to an increase in professional services related to \nour ongoing platform integrity efforts as well as marketing costs, partially offset by lower \nemployee compensation. \n \nG&A decreased 27%, driven mostly by lower legal-related costs. \n \nWe ended Q2 with over 75,900 employees, down 1% quarter-over-quarter as the vast majority of \nthe employees impacted by performance-related reductions earlier this year were no longer"),
 Document(metadata={'producer': 'Microsoft® Word for Microsoft 365', 'creator': 'Microsoft® Word for Microsoft 365', 'creationdate': '2025-07-30T21:31:06-04:00', 'source': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'file_path': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'total_pages': 19, 'format': 'PDF 1.7', 'title': 'META Q2 2025 Earnings Call Transcript', 'author': 'Kenneth Dorell;Jonathan Rong Li', 'subject': '', 'keywords': '', 'moddate': '2025-07-30T21:31:06-04:00', 'trapped': '', 'modDate': "D:20250730213106-04'00'", 'creationDate': "D:20250730213106-04'00'", 'page': 3}, page_content='4 \n \ncaptured in our headcount. This was partially offset by continued hiring in priority areas of \nmonetization, infrastructure, Reality Labs, AI, as well as regulation and compliance. \n  \nSecond quarter operating income was $20.4 billion, representing a 43% operating margin. \n \nOur tax rate for the quarter was 11%, which reflects excess tax benefits from share based \ncompensation due to the increase in our share price versus prior periods. \n \nNet income was $18.3 billion or $7.14 per share. \n \nCapital expenditures, including principal payments on finance leases, were $17.0 billion, driven by \ninvestments in servers, data centers and network infrastructure.  \n \nFree cash flow was $8.5 billion. We repurchased $9.8 billion of our Class A common stock and paid \n$1.3 billion in dividends to shareholders. We also made $15.1 billion in non-marketable equity \ninvestments in the second quarter, which includes our minority investment in Scale AI along with \nother investment activities. We ended the quarter with $47.1 billion in cash and marketable \nsecurities and $28.8 billion in debt. \n \nMoving now to our segment results.  \n \nI’ll begin with our Family of Apps segment. \n \nOur community across the Family of Apps continues to grow, and we estimate more than 3.4 \nbillion people used at least one of our Family of Apps on a daily basis in June. \n \nQ2 Total Family of Apps revenue was $47.1 billion, up 22% year-over-year. \n \nQ2 Family of Apps ad revenue was $46.6 billion, up 21% or 22% on a constant currency basis.  \n \nWithin ad revenue, the online commerce vertical was the largest contributor to year-over-year \ngrowth.  \n \nOn a user geography basis, ad revenue growth was strongest in Europe and Rest of World at 24% \nand 23%, respectively. North America and Asia-Pacific grew 21% and 18%. \n \nIn Q2, the total number of ad impressions served across our services increased 11%, with growth \nmainly driven by Asia-Pacific. Impression growth accelerated across all regions due primarily to \nengagement tailwinds on both Facebook and Instagram and, to a lesser extent, ad load \noptimizations on Facebook. The average price per ad increased 9%, benefiting from increased \nadvertiser demand, largely driven by improved ad performance. Pricing growth slowed modestly \nfrom the first quarter due to the accelerated impression growth in Q2.  \n \nFamily of Apps other revenue was $583 million, up 50%, driven by WhatsApp paid messaging \nrevenue growth as well as Meta Verified subscriptions. \n \nWe continue to direct the majority of our investments toward the development and operation of \nour Family of Apps. In Q2, Family of Apps expenses were $22.2 billion, representing 82% of our \noverall expenses. Family of Apps expenses were up 14%, mainly due to growth in employee \ncompensation and infrastructure costs, partially offset by lower legal-related costs.'),
 Document(metadata={'producer': 'Microsoft® Word for Microsoft 365', 'creator': 'Microsoft® Word for Microsoft 365', 'creationdate': '2025-07-30T21:31:06-04:00', 'source': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'file_path': '../assets/data/META-Q2-2025-Earnings-Call-Transcript.pdf', 'total_pages': 19, 'format': 'PDF 1.7', 'title': 'META Q2 2025 Earnings Call Transcript', 'author': 'Kenneth Dorell;Jonathan Rong Li', 'subject': '', 'keywords': '', 'moddate': '2025-07-30T21:31:06-04:00', 'trapped': '', 'modDate': "D:20250730213106-04'00'", 'creationDate': "D:20250730213106-04'00'", 'page': 4}, page_content='5 \n \n \nFamily of Apps operating income was $25.0 billion, representing a 53% operating margin.  \n \nWithin our Reality Labs segment, Q2 revenue was $370 million, up 5% year-over-year due to \nincreased sales of AI glasses, partially offset by lower Quest sales.  \n \nReality Labs expenses were $4.9 billion, up 1% year-over-year driven by higher non-headcount \nrelated technology development costs. \n \nReality Labs operating loss was $4.5 billion. \n \nTurning now to the business outlook. There are two primary factors that drive our revenue \nperformance: our ability to deliver engaging experiences for our community, and our effectiveness \nat monetizing that engagement over time.   \n \nOn the first, daily actives continue to grow across Facebook, Instagram and WhatsApp as we \nmake additional improvements to our recommendation systems and product experiences. \n \nWe continue to see momentum with video engagement in particular. In Q2, Instagram video time \nwas up more than 20% year-over-year globally. We’re seeing strong traction on Facebook as well, \nparticularly in the US where video time spent similarly expanded more than 20% year-over-year. \nThese gains have been enabled by ongoing optimizations to our ranking systems to better identify \nthe most relevant content to show. \n \nWe expect to deliver additional improvements throughout the year as we further scale up our \nmodels and make recommendations more adaptive to a person’s interests within their session. \nAnother emphasis of our recommendations work is promoting original content. On Instagram, \nover two-thirds of recommended content in the US now comes from original posts. In the second \nhalf, we’ll be focused on further increasing the freshness of original posts so the right audiences \ncan discover original content from creators soon after it is posted. \n \nWe are also making good progress on our longer-term ranking innovations that we expect will \nprovide the next leg of improvements over the coming years. Our research efforts to develop \ncross-surface foundation recommendation models continue to progress. We are also seeing \npromising results from using LLMs in Threads recommendation systems. The incorporation of \nLLMs are now driving a meaningful share of the ranking-related time spent gains on Threads. \nWe’re now exploring how to extend the use of LLMs in recommendation systems to our other \napps. We’re leveraging Llama in several other back-end processes as well, including actioning bug \nreports so we can identify and resolve recurring issues more quickly and efficiently. This has \nresulted in top-line bug reports in the US & Canada in Facebook Feed and Notifications dropping \nby roughly 30% over the past 10 months. \n \nThe primary way we’re using Llama in our apps today is to power Meta AI, which is now available \nin over 200 countries and territories. WhatsApp continues to be the largest driver of queries as \npeople message Meta AI directly for tasks such as information gathering, homework assistance, \nand generating images. Outside of WhatsApp, we’re seeing Meta AI become an increasingly \nvaluable complement to our content discovery engines. Meta AI usage on Facebook is expanding \nas people use it to ask about posts they see in Feed and find content across our platform in \nSearch. Another way we expect Meta AI will help with content discovery is through the automatic'),

In [43]:
# this document only has text. It does not contain any tables and images.
# Let's try if this module can extract those too.
# Starting with table extraction with a new document.

In [44]:
filename = "Nestlé-India-AR-2024-25.pdf"

In [45]:
loader = PyMuPDFLoader(
    file_path=data_directory+filename,
    extract_tables='html'
)

In [46]:
documents = loader.load() # Loads each page as one document.

Consider using the pymupdf_layout package for a greatly improved page layout analysis.

In [47]:
print(len(documents));documents[0:5]

287

[Document(metadata={'producer': 'iLovePDF', 'creator': 'Adobe InDesign 20.3 (Macintosh)', 'creationdate': '2025-06-02T23:01:57+05:30', 'source': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'file_path': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'total_pages': 287, 'format': 'PDF 1.7', 'title': '', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-06-02T23:15:43+05:30', 'trapped': '', 'modDate': "D:20250602231543+05'30'", 'creationDate': "D:20250602230157+05'30'", 'page': 0}, page_content='Adversity \nMakes Us \nStronger\nNestlé India Limited\nAnnual Report 2024-25'),
 Document(metadata={'producer': 'iLovePDF', 'creator': 'Adobe InDesign 20.3 (Macintosh)', 'creationdate': '2025-06-02T23:01:57+05:30', 'source': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'file_path': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'total_pages': 287, 'format': 'PDF 1.7', 'title': '', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-06-02T23:15:43+05:30', 'trapped': '', 'modDate': "D:20250602231543+05'30'", 'creationDate': "D:20250602230157+05'30'", 'page': 1}, page_content="Contents\nAnnexures to the Board's Report\n208\n228\n231\n295\n306\n309\n313\nAnnexure 1: \nReport on Corporate Governance\nAnnexure 2: \nAnnual Report on CSR Activities\nAnnexure 3A: \nBusiness Responsibility and \nSustainability Report\nAnnexure 3B: \nAssurance Report on BRSR Core\nAnnexure 4: \nSecretarial Audit Report\nAnnexure 5: \nReport on Conservation of Energy etc.\nAnnexure 6: \nInformation Regarding Employees and \nRelated Disclosures\nEvery morning as a new day \ndawns….8,629 employees in our \nfactories, fields and offices, \nwork with indefatigable zeal \nand a singular PURPOSE of \nserving our beloved consumers, \nwith a single pursuit of \nbringing products that are of \nunimpeachable quality.\nSuresh Narayanan\nChairman and Managing Director\nCautionary Statement\nStatements in this Annual Report, particularly \nthose which relate to Management Discussion and \nAnalysis as explained in the Corporate Governance \nReport, describing the Company’s objectives, \nprojections, estimates and expectations may \nconstitute ‘forward looking statements’ within the \nmeaning of applicable laws and regulations. Actual \nresults might differ materially from those either \nexpressed or implied in the statement depending \non the circumstances.\nAnnual Report 2024-25\n02\n04\n10\n20\n06\n36 \n12\n40\n68\n67\n64\n13\n54\n46\n18\n17\n16\n14\n62\n50\n83\nBoard of Directors\nAdversity Makes Us Stronger\nThe Decade That Was (2015-2025)\nProduct Portfolio\nChairman's Message\nIT Integration\nNestlé's India Story\nCorporate Social Responsibility\nBoard’s Report\nCorporate Information\nRisk and Opportunities\nBrand Footprint in India\nPlanet\nPeople\nSales\n10 - Year Financial Highlights\nNestlé India in Numbers\nNESPRESSO\nAwards and Recognitions \nPartnerships\nAnnual Accounts"),
 Document(metadata={'producer': 'iLovePDF', 'creator': 'Adobe InDesign 20.3 (Macintosh)', 'creationdate': '2025-06-02T23:01:57+05:30', 'source': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'file_path': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'total_pages': 287, 'format': 'PDF 1.7', 'title': '', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-06-02T23:15:43+05:30', 'trapped': '', 'modDate': "D:20250602231543+05'30'", 'creationDate': "D:20250602230157+05'30'", 'page': 2}, page_content='Board of Directors\n01\n02\n03\n04\n05\n06\n07\n08\n09\nMr. Sidharth Kumar Birla\nIndependent \nNon-Executive Director\n01__ \nMs. Anjali Bansal \nIndependent \nNon-Executive Director\n03__ \nMs. Suneeta Reddy  \nIndependent \nNon-Executive Director\n05__ \nMr. P. R. Ramesh \nIndependent \nNon-Executive Director\n07__ \nMr. Pramod Kumar Rai\nCompany Secretary and \nCompliance Officer\n09__ \nMs. Alpana Parida \nIndependent \nNon-Executive Director\n02__ \nMr. Suresh Narayanan\nChairman and  \nManaging Director\n04__ \nMs. Svetlana Boldina \nExecutive Director –  \nF&C and CFO\n06__ \nMr. Satish Srinivasan\nExecutive Director -  \nTechnical\n08__ \n03\nAnnual Report 2024-25\n02\nNestlé India Limited\nAdversity Makes Us Stronger\n\n\n<table border="1" class="dataframe">\n  <tbody>\n    <tr>\n      <td>None</td>\n      <td></td>\n      <td>NaN</td>\n      <td>None</td>\n    </tr>\n    <tr>\n      <td>None</td>\n      <td>01 Mr. Sidharth Kumar Birla 03 Ms. Anjali Bansal\\n__ __\\nIndependent Independent\\nNon-Executive Director Non-Executive Director\\n02 Ms. Alpana Parida 04 Mr. Suresh Narayanan\\n__ __\\nIndependent Chairman and\\nNon-Executive Director Managing Director</td>\n      <td>05 Ms. Suneeta Reddy 07 Mr. P. R. Ramesh 09 Mr. Pramod Kumar Rai\\n__ __ __\\nIndependent Independent Company Secretary and\\nNon-Executive Director Non-Executive Director Compliance Officer\\n06 Ms. Svetlana Boldina 08 Mr. Satish Srinivasan\\n__ __\\nExecutive Director – Executive Director -\\nF&amp;C and CFO Technical</td>\n      <td>None</td>\n    </tr>\n    <tr>\n      <td>None</td>\n      <td>02 Nestlé India Limited</td>\n      <td>Annual Report 2024-25 03</td>\n      <td>None</td>\n    </tr>\n  </tbody>\n</table>'),
 Document(metadata={'producer': 'iLovePDF', 'creator': 'Adobe InDesign 20.3 (Macintosh)', 'creationdate': '2025-06-02T23:01:57+05:30', 'source': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'file_path': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'total_pages': 287, 'format': 'PDF 1.7', 'title': '', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-06-02T23:15:43+05:30', 'trapped': '', 'modDate': "D:20250602231543+05'30'", 'creationDate': "D:20250602230157+05'30'", 'page': 3}, page_content="Adversity Makes Us Stronger\nOnly a purpose-led and motivated \nspirit can rise to any occasion and \ntriumph in the face of adversity. \nNestlé India is one such glowing \nprofile in resilience, perseverance \nand adaptability that has consistently \ndefied the odds and delivered.\nThis culture manifests \nin the exacting care \nundertaken in our \nprocurement processes, \nthe cutting-edge \nwherewithal and \nscience inherent in \nour products. Nestlé's \ntimeless commitment \nto the highest quality, \nstandards and nutrition \nwill always shine bright.\nEven in the most trying situations we \nnever forgot to treat one another with \nrespect. We used our strength to lift \nvulnerable communities. Our unflinching \nloyalty to our corporate conscience \nalways reflected Nestlé at its best.\nWe have been committed to India and \nto all our stakeholders for over 113 years \nand therefore our institutional character \nand commitment to the sacred Nestlé \nPurpose will ensure that irrespective \nof adversities that came yesterday, \nand may come again tomorrow, we \nwill always deliver to our expectations, \nthe ‘Nestlé Way’.   \n05\nAnnual Report 2024-25\n04\nNestlé India Limited"),
 Document(metadata={'producer': 'iLovePDF', 'creator': 'Adobe InDesign 20.3 (Macintosh)', 'creationdate': '2025-06-02T23:01:57+05:30', 'source': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'file_path': '../assets/data/Nestlé-India-AR-2024-25.pdf', 'total_pages': 287, 'format': 'PDF 1.7', 'title': '', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-06-02T23:15:43+05:30', 'trapped': '', 'modDate': "D:20250602231543+05'30'", 'creationDate': "D:20250602230157+05'30'", 'page': 4}, page_content='Chairman\'s Message\nAs I write my last shareholder letter, \nI feel overwhelmed with emotions – a \nsense of pride – a feeling of nostalgia \n– and immense gratitude as I look \nback at almost a decade of service in \nyour Company at the helm.\nIt was a decade that brought both \nopportunities and challenges. Times that were \nunpredictable, yet promising. Together we \nnavigated the black swans and gray rhinos. \nAnd seized the rising India opportunity. In the \nunpredictable dance of light and shadow, true \nresilience was forged.\nDear Members,\nWe kept our promise of unlocking the \npower of food, to enhance the quality \nof life for today and generations to \ncome. Encapsulated in our heartbeat \n- Purpose, People, Partnership, \nPlanet and Performance, we walked \nthe path of progress.\nSuresh Narayanan\nChairman and Managing Director\nFirst 100 Days – \nJuly 2015\nMy first 100 days as the \nChairman and Managing \nDirector of Nestlé India had been \none of the greatest challenges \nof my career. Yet they stand \nout as enriching experiences! \nConfronting the MAGGI crisis \nwas daunting. Every step \ntowards stability had its risks. Yet \nwe were bold with our TRUTH.\nIt was the brand TRUST of \nMAGGI and collective strength \nof our employees, partners, \ndistributors, suppliers and \nconsumers that helped your \nCompany bounce back \nwith renewed vigour.  \nTogether we \nemerged \nstronger!\nMAGGI noodles went from market \nleadership to near extinction and \nrecovered 60% of its market share \nwithin months of its relaunch.\nAt that time, a young brand \nmanager suggested ‘’why don’t we \nrelaunch MAGGI online?" I asked \nabout the risk of failure. After a \nquick assessment, we relaunched \nMAGGI online and the rest is \nhistory—60,000 boxes were sold in \nless than 5 minutes on Snapdeal.\nToday ‘Aapki MAGGI’ is the most \nloved and enjoyable brand. \nSometimes adversity pushes you \ninto a better destiny. I am reminded \nof Nobel laureate Rabindranath \nTagore\'s stirring lines from the \nGitanjali: “Let me not pray to be \nsheltered from dangers, but to \nbe fearless when facing them.” \nIt\'s in navigating the storm, \nnot avoiding it, that we often \nfind our truest north.\nOur journey has never been one of \nshort-cuts or settling for less.  \nWe made the right investments—\nnot just in assets, but in ideas and \npeople. And we made responsible \nchoices - choices that honored \nour values, sustained our growth. \nWe kept our promise of unlocking \nthe power of food, to enhance \nthe quality of life for today and \ngenerations to come. Encapsulated \nin our heartbeat - Purpose, \nPeople, Partnership, Planet \nand Performance, we walked \nthe path of progress.\nEvery morning as a new day \ndawns…8,629 employees in our \nfactories, fields and offices, work \nwith indefatigable zeal and a \nsingular PURPOSE of serving our \nbeloved consumers, with a single \npursuit of bringing products that \nare of unimpeachable quality and \nhighest safety standard.\nMoments and Milestones - \nTen Years of Service\nPerformance -  \nInnovations  - Value \nCreation\nWe live in capricious times. \nInflationary pressures. Muted \nconsumer demand. Tightening \nof the wallet. COVID a harbinger \nof economic slowdown, geo-\npolitical crisis - all wrapped up in \na decade of promise, challenges \nand unexpected opportunities. \nVolatilities will come and go, but it \nOver the last decade, our revenue \nwitnessed a CAGR of \n10.3% while the corresponding \nprofits from operations grew by \n13.5%. In the same period our \nmarket capitalization grew to  \n3.9 times and the \nTotal Shareholder Return \n(TSR) CAGR  was 17.0%. \nwas the strength of teams, brands \nand conviction that made us stand \nup to the odds and deliver \n10 years of consistent performance. \nJust 10 years ago 80,000 \nShareholders entrusted us with \na part of their future. Today, that \nincredible Shareholder Parivaar has \ngrown to over 550,000\nWe were once seen as an urban \nCompany with a limited portfolio, \nbut through penetration-led \nvolume growth strategy rolled \nout in 2015, we now have access \nto more households and more \nconsumption occasions.\nWe no longer fear failure! \nLaunching new products doesn’t \nhappen with a flip of switch! We \nunderstood the evolving pulse of \nthe consumer. Prioritized speed in \nexecution. Our pace of innovation \nis now four times faster than \nit was a decade ago.\nIn 2015, many considered us to be \nsolely a MAGGI noodles Company. \nSince then we recalibrated and \nrejuvenated the portfolio launching \nover 150+ new products that have \ncontributed to 7% of sales.  \nOur consumer metrics score went \nup in the last decade. \n07\nAnnual Report 2024-25\n06\nNestlé India Limited\nAdversity Makes Us Stronger')]

In [48]:
# Let us focus on the tables in the document.

- **Table with **
  
!["Source Table"](../assets/snapshots/extraction/tables/table_1.png)

In [49]:
print(documents[67].page_content)

(J in million)
Particulars
Notes
As at
31st March, 2025
As at
31st March, 2024
Current Liabilities
Financial liabilities

Borrowings
18
 7,308.6
 56.6

Lease liabilities
19
 719.8
 574.7

Trade payables


Total outstanding dues of micro enterprises and
small enterprises
22, 44
 4,170.9
 3,532.6


Total outstanding dues of creditors other than micro
enterprises and small enterprises
22
 19,564.4
 18,846.3

Payables for capital expenditure


Total outstanding dues of micro enterprises and
small enterprises
44
 430.3
 561.4


Total outstanding dues of creditors other than micro
enterprises and small enterprises
 2,072.5
 5,179.8

Other financial liabilities
23
 7,553.0
 6,417.2
Other current liabilities
21
 2,158.7
 1,393.8
Provisions
20
 2,422.8
 2,616.2
Current tax liabilities (net)
 452.5
 382.1
Total Current Liabilities
 46,853.5
 39,560.7
Total Liabilities
82,067.4
71,821.7
Total Equity and Liabilities
 123,238.9
 105,230.6
STANDALONE BALANCE SHEET AS AT 31st MARCH, 2025
See accompanying notes 1 to 48 forming part of the standalone financial statements
As per our report of even date attached	 For and on behalf of the Board of Directors
For S.R. Batliboi & Co. LLP
Chartered Accountants
Firm's Registration No. - 301003E/E300005
PANKAJ CHADHA
SURESH NARAYANAN	 SVETLANA BOLDINA
PRAMOD KUMAR RAI
Partner
Chairman and
Executive Director - Finance	 Company Secretary
Membership No. - 091813
Managing Director
& Control and CFO
Membership No. - FCS 4676

(DIN-07246738)
(DIN-10044338)
PAN-ABVPR5131P
24th April 2025
24th April 2025
Gurugram
Nanjangud
99
Annual Report 2024-25


<table border="1" class="dataframe">
  <tbody>
    <tr>
      <td>Notes</td>
      <td>As at\n31st March, 2025</td>
      <td>As at\n31st March, 2024</td>
    </tr>
    <tr>
      <td>18\n19\n22, 44\n22\n44\n23\n21\n20</td>
      <td></td>
      <td>56.6\n574.7\n3,532.6\n18,846.3\n561.4\n5,179.8\n6,417.2\n1,393.8\n2,616.2\n382.1</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td></td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>7,308.6</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>719.8</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td></td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>4,170.9</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>19,564.4</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td></td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>430.3</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>2,072.5</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>7,553.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>2,158.7</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>2,422.8</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>452.5</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>46,853.5</td>
      <td>39,560.7</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>82,067.4</td>
      <td>71,821.7</td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>123,238.9</td>
      <td>105,230.6</td>
    </tr>
  </tbody>
</table>

In [50]:
# The extraction was done as an html; all the rows are extracted at row level, 
# but if we wanted to recreate a table relation later, it cannot be done with this extraction,
# as we wouldn't know where the table starts. This is just a lazy ocr output that we are seeing.

In [51]:
# If it is diificult to understand, 
# think whether any application that is referring to this extraction 
# will it be able to answer the following question : what was the average of total liabilities?

# To answer this, AI needs to have knowledge to reconstruct it as a series, and then apply the average formula.
# It is not possible with this. Let us try other methods.

In [52]:
# METHOD 1: PDFPlumber

# PDFPlumber is simple, reliable, and returns tables as structured Python objects
# that can be easily converted to DataFrames, CSV, or JSON

In [53]:
import pdfplumber
import pandas as pd
import json

In [54]:
pdf_file = data_directory + filename

with pdfplumber.open(pdf_file) as pdf:
    for page_num, page in enumerate(pdf.pages):
        tables = page.extract_tables()

        if tables:
            print(f"\n=== Page {page_num + 1} has {len(tables)} table(s) ===")

=== Page 2 has 1 table(s) ===

=== Page 3 has 2 table(s) ===

=== Page 4 has 1 table(s) ===

=== Page 5 has 1 table(s) ===

=== Page 9 has 2 table(s) ===

=== Page 10 has 8 table(s) ===

=== Page 11 has 1 table(s) ===

=== Page 12 has 3 table(s) ===

=== Page 13 has 1 table(s) ===

=== Page 14 has 2 table(s) ===

=== Page 15 has 2 table(s) ===

=== Page 16 has 2 table(s) ===

=== Page 17 has 2 table(s) ===

=== Page 18 has 2 table(s) ===

=== Page 19 has 3 table(s) ===

=== Page 20 has 1 table(s) ===

=== Page 24 has 2 table(s) ===

=== Page 25 has 1 table(s) ===

=== Page 26 has 4 table(s) ===

=== Page 27 has 1 table(s) ===

=== Page 29 has 2 table(s) ===

=== Page 31 has 2 table(s) ===

=== Page 37 has 4 table(s) ===

=== Page 38 has 5 table(s) ===

=== Page 40 has 1 table(s) ===

=== Page 54 has 1 table(s) ===

=== Page 58 has 1 table(s) ===

=== Page 59 has 1 table(s) ===

=== Page 60 has 1 table(s) ===

=== Page 61 has 1 table(s) ===

=== Page 62 has 1 table(s) ===

=== Page 67 has 1 table(s) ===

=== Page 68 has 1 table(s) ===

=== Page 69 has 1 table(s) ===

=== Page 70 has 1 table(s) ===

=== Page 71 has 1 table(s) ===

=== Page 72 has 3 table(s) ===

=== Page 73 has 2 table(s) ===

=== Page 77 has 1 table(s) ===

=== Page 78 has 1 table(s) ===

=== Page 79 has 3 table(s) ===

=== Page 80 has 2 table(s) ===

=== Page 81 has 3 table(s) ===

=== Page 82 has 3 table(s) ===

=== Page 83 has 1 table(s) ===

=== Page 84 has 3 table(s) ===

=== Page 85 has 4 table(s) ===

=== Page 86 has 4 table(s) ===

=== Page 87 has 3 table(s) ===

=== Page 88 has 3 table(s) ===

=== Page 89 has 3 table(s) ===

=== Page 90 has 3 table(s) ===

=== Page 91 has 5 table(s) ===

=== Page 92 has 3 table(s) ===

=== Page 94 has 1 table(s) ===

=== Page 95 has 1 table(s) ===

=== Page 96 has 1 table(s) ===

=== Page 97 has 2 table(s) ===

=== Page 98 has 3 table(s) ===

=== Page 99 has 2 table(s) ===

=== Page 100 has 3 table(s) ===

=== Page 102 has 1 table(s) ===

=== Page 103 has 2 table(s) ===

=== Page 104 has 1 table(s) ===

=== Page 105 has 1 table(s) ===

=== Page 106 has 3 table(s) ===

=== Page 107 has 3 table(s) ===

=== Page 109 has 1 table(s) ===

=== Page 110 has 1 table(s) ===

=== Page 111 has 1 table(s) ===

=== Page 112 has 2 table(s) ===

=== Page 113 has 1 table(s) ===

=== Page 114 has 1 table(s) ===

=== Page 115 has 1 table(s) ===

=== Page 119 has 1 table(s) ===

=== Page 125 has 1 table(s) ===

=== Page 126 has 1 table(s) ===

=== Page 127 has 1 table(s) ===

=== Page 128 has 1 table(s) ===

=== Page 129 has 1 table(s) ===

=== Page 130 has 2 table(s) ===

=== Page 131 has 2 table(s) ===

=== Page 136 has 1 table(s) ===

=== Page 137 has 1 table(s) ===

=== Page 138 has 3 table(s) ===

=== Page 139 has 2 table(s) ===

=== Page 140 has 3 table(s) ===

=== Page 141 has 2 table(s) ===

=== Page 142 has 2 table(s) ===

=== Page 143 has 2 table(s) ===

=== Page 144 has 4 table(s) ===

=== Page 145 has 4 table(s) ===

=== Page 146 has 3 table(s) ===

=== Page 147 has 3 table(s) ===

=== Page 148 has 3 table(s) ===

=== Page 149 has 3 table(s) ===

=== Page 150 has 5 table(s) ===

=== Page 151 has 3 table(s) ===

=== Page 153 has 1 table(s) ===

=== Page 154 has 2 table(s) ===

=== Page 155 has 1 table(s) ===

=== Page 156 has 3 table(s) ===

=== Page 157 has 3 table(s) ===

=== Page 158 has 1 table(s) ===

=== Page 159 has 1 table(s) ===

=== Page 160 has 2 table(s) ===

=== Page 162 has 1 table(s) ===

=== Page 163 has 2 table(s) ===

=== Page 164 has 1 table(s) ===

=== Page 165 has 1 table(s) ===

=== Page 166 has 3 table(s) ===

=== Page 167 has 3 table(s) ===

=== Page 169 has 1 table(s) ===

=== Page 170 has 1 table(s) ===

=== Page 171 has 2 table(s) ===

=== Page 172 has 2 table(s) ===

=== Page 173 has 1 table(s) ===

=== Page 174 has 1 table(s) ===

=== Page 176 has 4 table(s) ===

=== Page 177 has 1 table(s) ===

=== Page 178 has 1 table(s) ===

=== Page 180 has 1 table(s) ===

=== Page 183 has 1 table(s) ===

=== Page 186 has 2 table(s) ===

=== Page 187 has 2 table(s) ===

=== Page 188 has 2 table(s) ===

=== Page 189 has 3 table(s) ===

=== Page 190 has 1 table(s) ===

=== Page 195 has 1 table(s) ===

=== Page 197 has 1 table(s) ===

=== Page 198 has 1 table(s) ===

=== Page 199 has 3 table(s) ===

=== Page 201 has 2 table(s) ===

=== Page 202 has 4 table(s) ===

=== Page 203 has 4 table(s) ===

=== Page 204 has 2 table(s) ===

=== Page 205 has 1 table(s) ===

=== Page 206 has 1 table(s) ===

=== Page 207 has 3 table(s) ===

=== Page 208 has 1 table(s) ===

=== Page 209 has 1 table(s) ===

=== Page 210 has 3 table(s) ===

=== Page 212 has 2 table(s) ===

=== Page 213 has 1 table(s) ===

=== Page 214 has 1 table(s) ===

=== Page 215 has 1 table(s) ===

=== Page 216 has 1 table(s) ===

=== Page 217 has 2 table(s) ===

=== Page 218 has 1 table(s) ===

=== Page 219 has 1 table(s) ===

=== Page 220 has 2 table(s) ===

=== Page 221 has 2 table(s) ===

=== Page 222 has 1 table(s) ===

=== Page 223 has 1 table(s) ===

=== Page 226 has 5 table(s) ===

=== Page 227 has 3 table(s) ===

=== Page 228 has 3 table(s) ===

=== Page 229 has 2 table(s) ===

=== Page 230 has 1 table(s) ===

=== Page 231 has 1 table(s) ===

=== Page 232 has 1 table(s) ===

=== Page 234 has 1 table(s) ===

=== Page 235 has 2 table(s) ===

=== Page 237 has 2 table(s) ===

=== Page 238 has 1 table(s) ===

=== Page 239 has 1 table(s) ===

=== Page 240 has 1 table(s) ===

=== Page 242 has 2 table(s) ===

=== Page 243 has 2 table(s) ===

=== Page 244 has 2 table(s) ===

=== Page 245 has 1 table(s) ===

=== Page 246 has 1 table(s) ===

=== Page 247 has 1 table(s) ===

=== Page 248 has 2 table(s) ===

=== Page 249 has 2 table(s) ===

=== Page 250 has 1 table(s) ===

=== Page 251 has 2 table(s) ===

=== Page 252 has 2 table(s) ===

=== Page 253 has 1 table(s) ===

=== Page 255 has 2 table(s) ===

=== Page 256 has 3 table(s) ===

=== Page 257 has 2 table(s) ===

=== Page 258 has 1 table(s) ===

=== Page 259 has 1 table(s) ===

=== Page 260 has 1 table(s) ===

=== Page 261 has 2 table(s) ===

=== Page 262 has 1 table(s) ===

=== Page 263 has 1 table(s) ===

=== Page 264 has 1 table(s) ===

=== Page 265 has 1 table(s) ===

=== Page 268 has 2 table(s) ===

=== Page 269 has 3 table(s) ===

=== Page 270 has 2 table(s) ===

=== Page 271 has 2 table(s) ===

=== Page 272 has 2 table(s) ===

=== Page 273 has 2 table(s) ===

=== Page 274 has 1 table(s) ===

=== Page 282 has 2 table(s) ===

In [55]:
# PDFPlumber - Convert Tables to Structured Formats
# Once extracted, tables can be stored in multiple formats for RAG:

def extract_and_structure_tables(pdf_path):
    """
    Extract tables from PDF and convert to structured formats
    Handles duplicate column names by making them unique.
    Returns: dict with page_number, table_index, dataframe, csv_string, json_string
    """
    from collections import Counter
    
    structured_tables = []
    
    def make_unique_columns(columns):
        """Handle duplicate column names by appending suffixes"""
        counts = Counter(columns)
        result = []
        column_counters = Counter()
        
        for col in columns:
            if counts[col] > 1:
                column_counters[col] += 1
                result.append(f"{col}_{column_counters[col]}")
            else:
                result.append(col)
        return result
    
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages):
            tables = page.extract_tables()
            
            if not tables:
                continue
            
            for table_idx, table in enumerate(tables):
                if len(table) < 2:  # Skip malformed tables
                    continue
                
                # Create DataFrame with original columns
                df = pd.DataFrame(table[1:], columns=table[0])
                original_columns = list(df.columns)
                
                # Make columns unique if needed
                unique_columns = make_unique_columns(original_columns)
                df.columns = unique_columns
                
                try:
                    # Store in multiple formats
                    structured_tables.append({
                        'page': page_num + 1,
                        'table_index': table_idx,
                        'dataframe': df,
                        'csv': df.to_csv(index=False),
                        'json': df.to_json(orient='records'),
                        'markdown': df.to_markdown(index=False),
                        'columns': unique_columns,
                        'original_columns': original_columns,
                        'rows': len(df),
                        'metadata': {
                            'source': pdf_path.split('/')[-1],
                            'page_number': page_num + 1,
                            'table_id': f"page_{page_num + 1}_table_{table_idx}",
                            'has_duplicate_columns': len(original_columns) != len(set(original_columns))
                        }
                    })
                except Exception as e:
                    print(f"Error processing table on page {page_num + 1}, table {table_idx}: {str(e)}")
                    continue
    
    return structured_tables

In [56]:
# Example usage
tables_data = extract_and_structure_tables(data_directory + filename)

In [57]:
# Summary of extracted tables
print(f"\nTotal tables extracted: {len(tables_data)}\n")
print("=" * 80)

for i, table_info in enumerate(tables_data[:3]):  # Show first 3 tables
    metadata = table_info['metadata']
    print(f"\nTable {i+1}: {metadata['table_id']}")
    print(f"  Has duplicate columns: {metadata['has_duplicate_columns']}")
    print(f"  Shape: {table_info['rows']} rows x {len(table_info['columns'])} columns")
    print(f"  Columns: {table_info['columns']}")
    print(f"  Original columns: {table_info['original_columns']}")
    print("\n  Data sample:")
    print(table_info['dataframe'].head(2))
    print("-" * 80)

Total tables extracted: 341

================================================================================

Table 1: page_10_table_0
  Has duplicate columns: False
  Shape: 19 rows x 11 columns
  Columns: ['Particulars', '2024-25', '2023-24^', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015*']
  Original columns: ['Particulars', '2024-25', '2023-24^', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015*']

  Data sample:
  Particulars  2024-25 2023-24^  2022  2021  2020  2019  2018  2017  2016  \
0              Results     None  None  None  None  None  None  None  None
1         NaN  200,775     None  None  None  None  None  None  None  None

  2015*
0  None
1  None
--------------------------------------------------------------------------------

Table 2: page_10_table_1
  Has duplicate columns: True
  Shape: 10 rows x 14 columns
  Columns: ['nan_1', 'nan_2', 'nan_3', 'nan_4', 'nan_5', 'nan_6', 'nan_7', 'nan_8', '42\n598,761', 'nan_9', 'nan_10', 'nan_11', 'nan_12', 'nan_13']
  Original columns: [nan, nan, nan, nan, nan, nan, nan, nan, '42\n598,761', nan, nan, nan, nan, nan]

  Data sample:
  nan_1 nan_2 nan_3 nan_4 nan_5 nan_6 nan_7 nan_8 42\n598,761 nan_9 nan_10  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN         NaN          NaN
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN         NaN

  nan_11 nan_12 nan_13
0           NaN    NaN
1    NaN    NaN    NaN
--------------------------------------------------------------------------------

Table 3: page_10_table_2
  Has duplicate columns: True
  Shape: 11 rows x 14 columns
  Columns: ['nan_1', 'nan_2', 'nan_3', 'nan_4', 'nan_5', 'nan_6', 'nan_7', ',35\n440011,,3344\n956,', 'nan_8', 'nan_9', 'nan_10', 'nan_11', 'nan_12', 'nan_13']
  Original columns: [nan, nan, nan, nan, nan, nan, nan, ',35\n440011,,3344\n956,', nan, nan, nan, nan, nan, nan]

  Data sample:
  nan_1 nan_2 nan_3 nan_4 nan_5 nan_6 nan_7 ,35\n440011,,3344\n956, nan_8  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN                     NaN
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN                     NaN   NaN

  nan_9  nan_10 nan_11 nan_12 nan_13
0   NaN     NaN    NaN    NaN    NaN
1        ,,3344    NaN           NaN
--------------------------------------------------------------------------------

In [58]:
# PRACTICAL USE CASES FOR EXTRACTED TABLES

# Use Case 1: Query answering with structured data
# Now you CAN answer questions like: "What was the average of total liabilities?"

# Example: Find numeric columns and compute aggregations
if tables_data:
    first_table = tables_data[0]
    df = first_table['dataframe']
    
    print("=" * 80)
    print(f"Table: {first_table['metadata']['table_id']}")
    print(f"Duplicate columns detected: {first_table['metadata']['has_duplicate_columns']}")
    print("=" * 80)
    
    # Find numeric columns
    numeric_cols = df.select_dtypes(include=['number']).columns.tolist()
    
    if numeric_cols:
        print(f"\nNumeric columns found: {numeric_cols}")
        print("\nPossible aggregations:")
        for col in numeric_cols[:3]:  # Show first 3
            try:
                values = pd.to_numeric(df[col], errors='coerce').dropna()
                if len(values) > 0:
                    print(f"  {col}:")
                    print(f"    - Mean: {values.mean():.2f}")
                    print(f"    - Sum: {values.sum():.2f}")
                    print(f"    - Min: {values.min():.2f}")
                    print(f"    - Max: {values.max():.2f}")
            except Exception as e:
                print(f"    Error computing stats: {str(e)}")
    
    # Use Case 2: Export for RAG system
    print("\n" + "=" * 80)
    print("EXPORTING FOR RAG SYSTEM:")
    print("=" * 80)
    
    # As structured JSON
    print("\n1. JSON Format (for API/vector DB):")
    print(f"   Size: {len(first_table['json'])} bytes")
    print(f"   First 200 chars: {first_table['json'][:200]}...")
    
    # As CSV
    print("\n2. CSV Format (for spreadsheet integration):")
    csv_lines = first_table['csv'].split('\n')
    print(f"   Rows: {len(csv_lines) - 1}")  # -1 for header
    print(f"   Headers: {csv_lines[0]}")
    
    # As Markdown
    print("\n3. Markdown Format (for documentation):")
    md_lines = first_table['markdown'].split('\n')
    for line in md_lines[:5]:
        print(f"   {line}")

================================================================================
Table: page_10_table_0
Duplicate columns detected: False
================================================================================

================================================================================
EXPORTING FOR RAG SYSTEM:
================================================================================

1. JSON Format (for API/vector DB):
   Size: 2932 bytes
   First 200 chars: [{"Particulars":"","2024-25":"Results","2023-24^":null,"2022":null,"2021":null,"2020":null,"2019":null,"2018":null,"2017":null,"2016":null,"2015*":null},{"Particulars":null,"2024-25":"200,775","2023-2...

2. CSV Format (for spreadsheet integration):
   Rows: 20
   Headers: Particulars,2024-25,2023-24^,2022,2021,2020,2019,2018,2017,2016,2015*

3. Markdown Format (for documentation):
   | Particulars   | 2024-25                               | 2023-24^   | 2022   | 2021   | 2020   | 2019   | 2018   | 2017   | 2016   | 2015*   |
   |:--------------|:--------------------------------------|:-----------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:--------|
   |               | Results                               |            |        |        |        |        |        |        |        |         |
   | nan           | 200,775                               |            |        |        |        |        |        |        |        |         |
   | nan           | 43,104                                |            |        |        |        |        |        |        |        |         |

In [59]:
# Load : 
# 
# pdf file containing text and tables and images
# Download file 1 from : https://www.nestle.in/sites/g/files/pydnoa451/files/2025-06/Nestl%C3%A9-India-AR-2024-25.pdf
# Download file 2 from : https://www.jpmorganchase.com/content/dam/jpmc/jpmorgan-chase-and-co/investor-relations/documents/annualreport-2024.pdf

In [60]:
# Let us now look if the document also has images.
# Some of the popular solutions that come via pip are :
# - Unstructured.io
# - Docling

# Apart from these, there are also ways using VLMs. 
# As it is going to be very costly in production with VLMs, it is often not deployed at scale in many companies.

In [61]:
import fitz  
from PIL import Image
import io
import hashlib
import numpy as np
from pathlib import Path

try:
    import cv2
except ImportError:
    print("OpenCV not installed, will use PIL for basic image analysis")
    cv2 = None

In [62]:
# Image Detection with PDFPlumber
# PDFPlumber provides a quick way to detect images and their positions

pdf_file = data_directory + filename

with pdfplumber.open(pdf_file) as pdf:
    print(f"Total pages: {len(pdf.pages)}\n")
    
    image_count = 0
    for page_num, page in enumerate(pdf.pages):
        # Get all images on the page
        images = page.images
        
        if images:
            image_count += len(images)
            print(f"Page {page_num + 1}: Found {len(images)} image(s)")
            
            for img_idx, img in enumerate(images):
                # img is a dict with keys: top, bottom, left, right, width, height, srcsize
                print(f"  Image {img_idx + 1}:")
                print(f"    Position: ({img['x0']:.1f}, {img['top']:.1f})")
                print(f"    Size: {img['width']:.1f}x{img['height']:.1f}")
                print(f"    Source size: {img.get('srcsize', 'Unknown')}")

print(f"\nTotal images found: {image_count}")

Total pages: 287

Page 1: Found 1 image(s)
  Image 1:
    Position: (-1.0, -1.0)
    Size: 557.9x776.1
    Source size: (2325, 3234)
Page 2: Found 19 image(s)
  Image 1:
    Position: (289.8, 248.1)
    Size: 127.9x127.9
    Source size: (256, 256)
  Image 2:
    Position: (319.3, 154.6)
    Size: 184.6x277.0
    Source size: (370, 554)
  Image 3:
    Position: (11.3, 574.5)
    Size: 222.3x52.2
    Source size: (444, 101)
  Image 4:
    Position: (52.8, 624.4)
    Size: 135.5x40.1
    Source size: (271, 81)
  Image 5:
    Position: (289.4, 477.8)
    Size: 216.0x223.3
    Source size: (432, 447)
  Image 6:
    Position: (174.3, 615.9)
    Size: 169.3x97.8
    Source size: (339, 196)
  Image 7:
    Position: (329.2, 58.8)
    Size: 77.2x94.8
    Source size: (155, 190)
  Image 8:
    Position: (383.2, 80.8)
    Size: 73.4x97.4
    Source size: (147, 195)
  Image 9:
    Position: (435.1, 100.2)
    Size: 73.3x98.7
    Source size: (147, 198)
  Image 10:
    Position: (65.2, 62.1)
    Size: 205.3x131.1
    Source size: (411, 263)
  Image 11:
    Position: (46.4, 88.0)
    Size: 80.6x105.3
    Source size: (162, 211)
  Image 12:
    Position: (58.4, 372.6)
    Size: 95.1x189.2
    Source size: (191, 379)
  Image 13:
    Position: (126.6, 402.6)
    Size: 144.0x154.9
    Source size: (289, 310)
  Image 14:
    Position: (269.5, 101.2)
    Size: 103.0x103.0
    Source size: (207, 207)
  Image 15:
    Position: (62.9, 253.5)
    Size: 54.9x100.2
    Source size: (110, 201)
  Image 16:
    Position: (224.9, 252.5)
    Size: 54.5x99.0
    Source size: (110, 199)
  Image 17:
    Position: (105.4, 235.3)
    Size: 53.2x118.4
    Source size: (107, 237)
  Image 18:
    Position: (183.4, 233.6)
    Size: 55.5x120.3
    Source size: (111, 241)
  Image 19:
    Position: (141.8, 235.0)
    Size: 58.6x118.9
    Source size: (118, 238)
Page 3: Found 1 image(s)
  Image 1:
    Position: (-1.0, -1.1)
    Size: 1113.8x629.9
    Source size: (2228, 1260)
Page 4: Found 1 image(s)
  Image 1:
    Position: (-1.0, -1.2)
    Size: 1113.8x776.3
    Source size: (2228, 1553)
Page 5: Found 2 image(s)
  Image 1:
    Position: (288.6, 55.6)
    Size: 794.2x674.1
    Source size: (1589, 1349)
  Image 2:
    Position: (-1.0, 103.8)
    Size: 501.3x368.5
    Source size: (1003, 738)
Page 8: Found 14 image(s)
  Image 1:
    Position: (-1.1, -1.2)
    Size: 558.2x776.4
    Source size: (1117, 1553)
  Image 2:
    Position: (760.8, 394.8)
    Size: 151.7x201.4
    Source size: (304, 403)
  Image 3:
    Position: (918.8, 394.8)
    Size: 151.4x201.3
    Source size: (303, 403)
  Image 4:
    Position: (611.2, 394.8)
    Size: 143.3x201.4
    Source size: (287, 403)
  Image 5:
    Position: (760.8, 137.0)
    Size: 151.5x200.2
    Source size: (303, 401)
  Image 6:
    Position: (918.7, 136.5)
    Size: 151.5x189.7
    Source size: (303, 380)
  Image 7:
    Position: (304.5, 428.3)
    Size: 196.0x176.3
    Source size: (393, 353)
  Image 8:
    Position: (611.2, 136.0)
    Size: 143.2x201.4
    Source size: (287, 403)
  Image 9:
    Position: (660.7, 268.8)
    Size: 65.1x106.4
    Source size: (131, 213)
  Image 10:
    Position: (783.5, 279.8)
    Size: 78.8x91.9
    Source size: (158, 184)
  Image 11:
    Position: (911.3, 306.6)
    Size: 108.8x75.3
    Source size: (218, 151)
  Image 12:
    Position: (786.8, 554.3)
    Size: 82.6x84.0
    Source size: (166, 168)
  Image 13:
    Position: (909.9, 542.8)
    Size: 147.5x105.1
    Source size: (295, 211)
  Image 14:
    Position: (661.5, 513.7)
    Size: 74.1x119.3
    Source size: (236, 58)
Page 9: Found 2 image(s)
  Image 1:
    Position: (330.9, 127.6)
    Size: 781.8x530.2
    Source size: (1564, 1061)
  Image 2:
    Position: (109.9, 454.1)
    Size: 287.0x287.0
    Source size: (574, 574)
Page 11: Found 3 image(s)
  Image 1:
    Position: (611.5, 419.9)
    Size: 458.7x308.8
    Source size: (918, 618)
  Image 2:
    Position: (200.4, 412.4)
    Size: 298.7x166.3
    Source size: (598, 333)
  Image 3:
    Position: (199.4, 593.8)
    Size: 60.1x60.1
    Source size: (121, 121)
Page 12: Found 14 image(s)
  Image 1:
    Position: (-1.0, -1.1)
    Size: 558.2x430.2
    Source size: (1117, 861)
  Image 2:
    Position: (41.5, 558.9)
    Size: 60.2x60.2
    Source size: (121, 121)
  Image 3:
    Position: (739.2, 102.9)
    Size: 87.3x106.1
    Source size: (175, 213)
  Image 4:
    Position: (807.9, 148.2)
    Size: 107.6x121.9
    Source size: (216, 244)
  Image 5:
    Position: (664.4, 140.2)
    Size: 96.8x134.1
    Source size: (194, 269)
  Image 6:
    Position: (890.2, 200.3)
    Size: 38.7x70.7
    Source size: (78, 142)
  Image 7:
    Position: (1004.2, 199.6)
    Size: 39.0x70.2
    Source size: (79, 141)
  Image 8:
    Position: (920.1, 187.5)
    Size: 37.5x83.5
    Source size: (76, 168)
  Image 9:
    Position: (975.1, 186.4)
    Size: 39.1x84.8
    Source size: (79, 170)
  Image 10:
    Position: (945.8, 187.3)
    Size: 41.3x83.9
    Source size: (83, 168)
  Image 11:
    Position: (770.7, 187.7)
    Size: 74.9x80.0
    Source size: (150, 161)
  Image 12:
    Position: (727.6, 198.1)
    Size: 71.4x75.3
    Source size: (143, 151)
  Image 13:
    Position: (638.8, 224.1)
    Size: 56.0x48.0
    Source size: (112, 96)
  Image 14:
    Position: (780.7, 318.1)
    Size: 258.0x350.1
    Source size: (516, 701)
Page 13: Found 4 image(s)
  Image 1:
    Position: (611.5, 350.0)
    Size: 458.7x204.5
    Source size: (918, 410)
  Image 2:
    Position: (41.5, 112.7)
    Size: 458.7x313.8
    Source size: (918, 628)
  Image 3:
    Position: (203.3, 344.5)
    Size: 302.7x430.8
    Source size: (606, 862)
  Image 4:
    Position: (612.5, 609.5)
    Size: 58.1x60.1
    Source size: (117, 121)
Page 14: Found 4 image(s)
  Image 1:
    Position: (-1.1, -1.1)
    Size: 556.8x430.3
    Source size: (1114, 861)
  Image 2:
    Position: (634.7, 101.0)
    Size: 393.4x230.4
    Source size: (787, 461)
  Image 3:
    Position: (41.6, 631.0)
    Size: 59.9x60.1
    Source size: (120, 121)
  Image 4:
    Position: (612.6, 533.8)
    Size: 218.3x119.8
    Source size: (437, 240)
Page 15: Found 4 image(s)
  Image 1:
    Position: (-1.1, -1.1)
    Size: 558.1x430.3
    Source size: (1117, 861)
  Image 2:
    Position: (41.4, 605.7)
    Size: 60.2x60.2
    Source size: (121, 121)
  Image 3:
    Position: (612.5, 374.3)
    Size: 418.9x235.8
    Source size: (838, 472)
  Image 4:
    Position: (663.9, 87.9)
    Size: 353.8x199.0
    Source size: (708, 399)
Page 16: Found 5 image(s)
  Image 1:
    Position: (-1.1, -1.2)
    Size: 558.2x430.5
    Source size: (1117, 862)
  Image 2:
    Position: (44.6, 581.4)
    Size: 53.9x57.8
    Source size: (108, 116)
  Image 3:
    Position: (849.9, 420.0)
    Size: 220.3x173.2
    Source size: (441, 347)
  Image 4:
    Position: (611.4, 519.9)
    Size: 220.5x210.0
    Source size: (441, 420)
  Image 5:
    Position: (619.8, 84.7)
    Size: 442.1x197.3
    Source size: (885, 395)
Page 17: Found 4 image(s)
  Image 1:
    Position: (-1.0, -1.4)
    Size: 558.2x430.6
    Source size: (1117, 862)
  Image 2:
    Position: (41.5, 571.5)
    Size: 60.1x59.5
    Source size: (121, 120)
  Image 3:
    Position: (611.5, 582.3)
    Size: 220.4x147.3
    Source size: (441, 295)
  Image 4:
    Position: (621.7, 85.8)
    Size: 424.5x210.7
    Source size: (849, 422)
Page 18: Found 9 image(s)
  Image 1:
    Position: (-1.1, -1.3)
    Size: 558.2x430.6
    Source size: (1117, 862)
  Image 2:
    Position: (45.9, 596.9)
    Size: 55.4x60.2
    Source size: (111, 121)
  Image 3:
    Position: (612.5, 486.2)
    Size: 218.3x115.8
    Source size: (437, 232)
  Image 4:
    Position: (864.5, 126.2)
    Size: 152.3x152.6
    Source size: (305, 306)
  Image 5:
    Position: (627.3, 124.4)
    Size: 91.1x157.1
    Source size: (183, 315)
  Image 6:
    Position: (690.9, 127.5)
    Size: 84.3x144.8
    Source size: (169, 290)
  Image 7:
    Position: (823.4, 126.7)
    Size: 86.3x143.5
    Source size: (173, 288)
  Image 8:
    Position: (750.1, 105.6)
    Size: 98.5x164.7
    Source size: (197, 330)
  Image 9:
    Position: (966.8, 174.7)
    Size: 76.8x101.5
    Source size: (154, 203)
Page 19: Found 9 image(s)
  Image 1:
    Position: (-1.1, -1.0)
    Size: 558.1x430.2
    Source size: (1117, 861)
  Image 2:
    Position: (41.5, 583.9)
    Size: 60.1x58.3
    Source size: (121, 117)
  Image 3:
    Position: (612.5, 619.9)
    Size: 218.3x109.8
    Source size: (437, 220)
  Image 4:
    Position: (973.0, 193.8)
    Size: 70.1x67.8
    Source size: (141, 136)
  Image 5:
    Position: (715.9, 97.4)
    Size: 178.5x207.5
    Source size: (358, 415)
  Image 6:
    Position: (621.9, 138.2)
    Size: 113.2x133.6
    Source size: (227, 268)
  Image 7:
    Position: (666.4, 176.6)
    Size: 98.0x95.1
    Source size: (196, 191)
  Image 8:
    Position: (922.2, 161.5)
    Size: 70.9x102.8
    Source size: (142, 206)
  Image 9:
    Position: (849.8, 193.1)
    Size: 88.0x66.2
    Source size: (177, 133)
Page 20: Found 2 image(s)
  Image 1:
    Position: (-1.1, -1.0)
    Size: 558.1x430.2
    Source size: (1117, 861)
  Image 2:
    Position: (41.5, 570.5)
    Size: 60.2x60.2
    Source size: (121, 121)
Page 21: Found 3 image(s)
  Image 1:
    Position: (611.5, 409.0)
    Size: 458.4x310.3
    Source size: (621, 917)
  Image 2:
    Position: (611.5, 157.1)
    Size: 458.7x221.9
    Source size: (918, 444)
  Image 3:
    Position: (41.4, 466.7)
    Size: 458.8x263.0
    Source size: (918, 526)
Page 22: Found 2 image(s)
  Image 1:
    Position: (-1.0, -1.1)
    Size: 558.0x423.1
    Source size: (1117, 847)
  Image 2:
    Position: (613.3, 487.6)
    Size: 456.9x242.1
    Source size: (914, 485)
Page 23: Found 3 image(s)
  Image 1:
    Position: (279.8, 206.8)
    Size: 220.3x164.5
    Source size: (441, 330)
  Image 2:
    Position: (611.5, 265.9)
    Size: 458.3x203.6
    Source size: (917, 408)
  Image 3:
    Position: (279.8, 447.6)
    Size: 220.4x222.8
    Source size: (441, 446)
Page 24: Found 3 image(s)
  Image 1:
    Position: (279.9, 547.5)
    Size: 220.3x172.1
    Source size: (441, 345)
  Image 2:
    Position: (279.9, 114.7)
    Size: 220.4x174.7
    Source size: (441, 350)
  Image 3:
    Position: (869.0, 303.8)
    Size: 79.1x78.9
    Source size: (159, 158)
Page 25: Found 4 image(s)
  Image 1:
    Position: (-1.1, -1.0)
    Size: 558.2x429.1
    Source size: (1117, 859)
  Image 2:
    Position: (42.6, 622.2)
    Size: 58.5x60.0
    Source size: (118, 121)
  Image 3:
    Position: (611.5, 470.2)
    Size: 458.7x259.5
    Source size: (918, 519)
  Image 4:
    Position: (612.5, 319.1)
    Size: 218.3x131.2
    Source size: (437, 263)
Page 26: Found 5 image(s)
  Image 1:
    Position: (611.5, 344.6)
    Size: 60.2x60.2
    Source size: (121, 121)
  Image 2:
    Position: (849.9, 344.6)
    Size: 60.1x60.1
    Source size: (121, 121)
  Image 3:
    Position: (38.5, 378.9)
    Size: 464.8x354.8
    Source size: (924, 702)
  Image 4:
    Position: (612.5, 602.8)
    Size: 456.6x126.9
    Source size: (914, 254)
  Image 5:
    Position: (280.9, 86.7)
    Size: 58.1x58.6
    Source size: (117, 118)
Page 27: Found 3 image(s)
  Image 1:
    Position: (-1.0, -1.1)
    Size: 558.0x430.3
    Source size: (1116, 861)
  Image 2:
    Position: (44.2, 614.2)
    Size: 56.4x60.1
    Source size: (113, 121)
  Image 3:
    Position: (849.9, 291.7)
    Size: 220.3x179.1
    Source size: (441, 359)
Page 28: Found 2 image(s)
  Image 1:
    Position: (41.3, 179.8)
    Size: 459.1x217.0
    Source size: (919, 435)
  Image 2:
    Position: (554.8, -1.0)
    Size: 557.9x776.1
    Source size: (1116, 1553)
Page 29: Found 3 image(s)
  Image 1:
    Position: (-1.1, 0.8)
    Size: 558.1x391.4
    Source size: (1117, 783)
  Image 2:
    Position: (611.5, 519.2)
    Size: 458.7x210.5
    Source size: (918, 421)
  Image 3:
    Position: (41.4, 593.7)
    Size: 60.3x60.3
    Source size: (121, 121)
Page 30: Found 1 image(s)
  Image 1:
    Position: (859.3, 75.2)
    Size: 200.8x123.0
    Source size: (402, 247)
Page 31: Found 2 image(s)
  Image 1:
    Position: (279.8, 350.5)
    Size: 194.8x262.8
    Source size: (526, 390)
  Image 2:
    Position: (611.4, 450.5)
    Size: 220.5x241.1
    Source size: (442, 483)
Page 32: Found 2 image(s)
  Image 1:
    Position: (279.8, 56.7)
    Size: 555.1x672.9
    Source size: (1346, 1111)
  Image 2:
    Position: (41.2, 191.9)
    Size: 221.0x336.2
    Source size: (443, 673)
Page 33: Found 1 image(s)
  Image 1:
    Position: (-1.2, 107.7)
    Size: 1114.2x621.3
    Source size: (2229, 1243)
Page 287: Found 1 image(s)
  Image 1:
    Position: (-1.1, -1.3)
    Size: 557.0x776.6
    Source size: (1554, 1114)

Total images found: 133

In [63]:
# We can get the bbox for each and every image in the pdf. 
# This can be used to extract specific images if required.

In [64]:
# Detailed Image Extraction with PyMuPDF
# PyMuPDF (fitz) gives access to image XObjects and their metadata

pdf_file_path = data_directory + filename
doc = fitz.open(pdf_file_path)

print(f"Total pages: {len(doc)}\n")

image_metadata = []

for page_num in range(len(doc)):
    page = doc[page_num]
    
    # Get all image XObjects on the page
    image_list = page.get_images()
    
    if image_list:
        print(f"Page {page_num + 1}: Found {len(image_list)} image(s)")
        
        for img_index, img_ref in enumerate(image_list):
            # img_ref is a tuple: (xref_number,)
            xref = img_ref[0]
            
            # Get image information
            pix = fitz.Pixmap(doc, xref)
            
            # Extract basic metadata
            img_info = {
                'page': page_num + 1,
                'image_index': img_index,
                'xref': xref,
                'width': pix.width,
                'height': pix.height,
                'size_pixels': pix.width * pix.height,
                'n': pix.n,  # Number of components (3=RGB, 4=RGBA, 1=Gray, etc.)
                'colorspace': pix.colorspace.name if pix.colorspace else None,
                'alpha': pix.alpha,  # Has alpha channel
            }
            
            # Get image bytes and calculate compressed size
            img_bytes = pix.tobytes()
            img_info['uncompressed_bytes'] = len(img_bytes)
            
            # Calculate image hash for deduplication
            img_info['hash'] = hashlib.md5(img_bytes).hexdigest()
            
            # Get aspect ratio
            img_info['aspect_ratio'] = pix.width / pix.height if pix.height > 0 else 0
            
            print(f"  Image {img_index + 1}:")
            print(f"    Dimensions: {img_info['width']}x{img_info['height']} px")
            print(f"    Colorspace: {img_info['colorspace']}")
            print(f"    Size: {img_info['uncompressed_bytes'] / 1024:.1f} KB")
            print(f"    Aspect ratio: {img_info['aspect_ratio']:.2f}")
            
            image_metadata.append(img_info)
            
            # Clean up
            pix = None

doc.close()
print(f"\nTotal images extracted: {len(image_metadata)}")

Total pages: 287

Page 1: Found 1 image(s)
  Image 1:
    Dimensions: 2325x3234 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 7128.0 KB
    Aspect ratio: 0.72
Page 2: Found 19 image(s)
  Image 1:
    Dimensions: 256x256 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 83.6 KB
    Aspect ratio: 1.00
  Image 2:
    Dimensions: 370x554 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 161.3 KB
    Aspect ratio: 0.67
  Image 3:
    Dimensions: 191x379 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 115.5 KB
    Aspect ratio: 0.50
  Image 4:
    Dimensions: 289x310 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 129.3 KB
    Aspect ratio: 0.93
  Image 5:
    Dimensions: 207x207 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 74.8 KB
    Aspect ratio: 1.00
  Image 6:
    Dimensions: 110x201 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 43.4 KB
    Aspect ratio: 0.55
  Image 7:
    Dimensions: 110x199 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 49.0 KB
    Aspect ratio: 0.55
  Image 8:
    Dimensions: 107x237 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 54.1 KB
    Aspect ratio: 0.45
  Image 9:
    Dimensions: 111x241 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 52.0 KB
    Aspect ratio: 0.46
  Image 10:
    Dimensions: 118x238 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 50.2 KB
    Aspect ratio: 0.50
  Image 11:
    Dimensions: 444x101 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 96.9 KB
    Aspect ratio: 4.40
  Image 12:
    Dimensions: 271x81 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 50.5 KB
    Aspect ratio: 3.35
  Image 13:
    Dimensions: 339x196 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 59.3 KB
    Aspect ratio: 1.73
  Image 14:
    Dimensions: 155x190 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 57.5 KB
    Aspect ratio: 0.82
  Image 15:
    Dimensions: 147x195 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 58.6 KB
    Aspect ratio: 0.75
  Image 16:
    Dimensions: 147x198 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 56.7 KB
    Aspect ratio: 0.74
  Image 17:
    Dimensions: 411x263 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 142.9 KB
    Aspect ratio: 1.56
  Image 18:
    Dimensions: 162x211 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 65.0 KB
    Aspect ratio: 0.77
  Image 19:
    Dimensions: 432x447 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 142.9 KB
    Aspect ratio: 0.97
Page 3: Found 1 image(s)
  Image 1:
    Dimensions: 2228x1260 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 3729.1 KB
    Aspect ratio: 1.77
Page 4: Found 1 image(s)
  Image 1:
    Dimensions: 2228x1553 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 3750.5 KB
    Aspect ratio: 1.43
Page 5: Found 2 image(s)
  Image 1:
    Dimensions: 1003x738 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1488.3 KB
    Aspect ratio: 1.36
  Image 2:
    Dimensions: 1589x1349 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 71.2 KB
    Aspect ratio: 1.18
Page 8: Found 14 image(s)
  Image 1:
    Dimensions: 1117x1553 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 71.3 KB
    Aspect ratio: 0.72
  Image 2:
    Dimensions: 393x353 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 298.2 KB
    Aspect ratio: 1.11
  Image 3:
    Dimensions: 131x213 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 60.0 KB
    Aspect ratio: 0.62
  Image 4:
    Dimensions: 158x184 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 55.2 KB
    Aspect ratio: 0.86
  Image 5:
    Dimensions: 218x151 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 52.1 KB
    Aspect ratio: 1.44
  Image 6:
    Dimensions: 166x168 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 55.2 KB
    Aspect ratio: 0.99
  Image 7:
    Dimensions: 295x211 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 67.1 KB
    Aspect ratio: 1.40
  Image 8:
    Dimensions: 236x58 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 35.6 KB
    Aspect ratio: 4.07
  Image 9:
    Dimensions: 304x403 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 173.9 KB
    Aspect ratio: 0.75
  Image 10:
    Dimensions: 303x403 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 232.5 KB
    Aspect ratio: 0.75
  Image 11:
    Dimensions: 287x403 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 231.5 KB
    Aspect ratio: 0.71
  Image 12:
    Dimensions: 287x403 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 83.2 KB
    Aspect ratio: 0.71
  Image 13:
    Dimensions: 303x401 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 190.2 KB
    Aspect ratio: 0.76
  Image 14:
    Dimensions: 303x380 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 128.8 KB
    Aspect ratio: 0.80
Page 9: Found 2 image(s)
  Image 1:
    Dimensions: 1564x1061 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 2307.4 KB
    Aspect ratio: 1.47
  Image 2:
    Dimensions: 574x574 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 152.9 KB
    Aspect ratio: 1.00
Page 11: Found 3 image(s)
  Image 1:
    Dimensions: 918x618 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 946.2 KB
    Aspect ratio: 1.49
  Image 2:
    Dimensions: 598x333 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 481.7 KB
    Aspect ratio: 1.80
  Image 3:
    Dimensions: 121x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 23.4 KB
    Aspect ratio: 1.00
Page 12: Found 14 image(s)
  Image 1:
    Dimensions: 1117x861 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1945.7 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 121x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 24.1 KB
    Aspect ratio: 1.00
  Image 3:
    Dimensions: 150x161 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 45.0 KB
    Aspect ratio: 0.93
  Image 4:
    Dimensions: 143x151 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 43.0 KB
    Aspect ratio: 0.95
  Image 5:
    Dimensions: 112x96 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 21.5 KB
    Aspect ratio: 1.17
  Image 6:
    Dimensions: 516x701 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 759.9 KB
    Aspect ratio: 0.74
  Image 7:
    Dimensions: 175x213 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 82.8 KB
    Aspect ratio: 0.82
  Image 8:
    Dimensions: 216x244 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 110.7 KB
    Aspect ratio: 0.89
  Image 9:
    Dimensions: 194x269 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 95.1 KB
    Aspect ratio: 0.72
  Image 10:
    Dimensions: 78x142 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 26.1 KB
    Aspect ratio: 0.55
  Image 11:
    Dimensions: 79x141 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 27.6 KB
    Aspect ratio: 0.56
  Image 12:
    Dimensions: 76x168 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 31.1 KB
    Aspect ratio: 0.45
  Image 13:
    Dimensions: 79x170 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 28.8 KB
    Aspect ratio: 0.46
  Image 14:
    Dimensions: 83x168 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 29.7 KB
    Aspect ratio: 0.49
Page 13: Found 4 image(s)
  Image 1:
    Dimensions: 918x410 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 803.8 KB
    Aspect ratio: 2.24
  Image 2:
    Dimensions: 918x628 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 928.0 KB
    Aspect ratio: 1.46
  Image 3:
    Dimensions: 606x862 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 630.6 KB
    Aspect ratio: 0.70
  Image 4:
    Dimensions: 117x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 23.0 KB
    Aspect ratio: 0.97
Page 14: Found 4 image(s)
  Image 1:
    Dimensions: 1114x861 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1322.6 KB
    Aspect ratio: 1.29
  Image 2:
    Dimensions: 787x461 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 481.3 KB
    Aspect ratio: 1.71
  Image 3:
    Dimensions: 120x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 22.8 KB
    Aspect ratio: 0.99
  Image 4:
    Dimensions: 437x240 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 264.4 KB
    Aspect ratio: 1.82
Page 15: Found 4 image(s)
  Image 1:
    Dimensions: 1117x861 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 896.2 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 121x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 25.8 KB
    Aspect ratio: 1.00
  Image 3:
    Dimensions: 838x472 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 506.5 KB
    Aspect ratio: 1.78
  Image 4:
    Dimensions: 708x399 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 458.3 KB
    Aspect ratio: 1.77
Page 16: Found 5 image(s)
  Image 1:
    Dimensions: 1117x862 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1423.6 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 108x116 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 26.5 KB
    Aspect ratio: 0.93
  Image 3:
    Dimensions: 441x347 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 348.4 KB
    Aspect ratio: 1.27
  Image 4:
    Dimensions: 441x420 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 217.3 KB
    Aspect ratio: 1.05
  Image 5:
    Dimensions: 885x395 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 550.6 KB
    Aspect ratio: 2.24
Page 17: Found 4 image(s)
  Image 1:
    Dimensions: 1117x862 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1052.3 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 121x120 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 25.0 KB
    Aspect ratio: 1.01
  Image 3:
    Dimensions: 441x295 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 251.9 KB
    Aspect ratio: 1.49
  Image 4:
    Dimensions: 849x422 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 503.1 KB
    Aspect ratio: 2.01
Page 18: Found 9 image(s)
  Image 1:
    Dimensions: 1117x862 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 2158.9 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 111x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 23.7 KB
    Aspect ratio: 0.92
  Image 3:
    Dimensions: 437x232 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 217.2 KB
    Aspect ratio: 1.88
  Image 4:
    Dimensions: 305x306 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 117.6 KB
    Aspect ratio: 1.00
  Image 5:
    Dimensions: 183x315 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 64.7 KB
    Aspect ratio: 0.58
  Image 6:
    Dimensions: 169x290 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 84.0 KB
    Aspect ratio: 0.58
  Image 7:
    Dimensions: 173x288 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 99.3 KB
    Aspect ratio: 0.60
  Image 8:
    Dimensions: 197x330 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 107.4 KB
    Aspect ratio: 0.60
  Image 9:
    Dimensions: 154x203 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 53.6 KB
    Aspect ratio: 0.76
Page 19: Found 9 image(s)
  Image 1:
    Dimensions: 1117x861 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1217.2 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 121x117 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 23.3 KB
    Aspect ratio: 1.03
  Image 3:
    Dimensions: 437x220 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 214.9 KB
    Aspect ratio: 1.99
  Image 4:
    Dimensions: 141x136 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 42.0 KB
    Aspect ratio: 1.04
  Image 5:
    Dimensions: 358x415 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 120.7 KB
    Aspect ratio: 0.86
  Image 6:
    Dimensions: 227x268 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 49.0 KB
    Aspect ratio: 0.85
  Image 7:
    Dimensions: 196x191 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 25.8 KB
    Aspect ratio: 1.03
  Image 8:
    Dimensions: 142x206 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 58.9 KB
    Aspect ratio: 0.69
  Image 9:
    Dimensions: 177x133 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 57.2 KB
    Aspect ratio: 1.33
Page 20: Found 2 image(s)
  Image 1:
    Dimensions: 1117x861 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1248.9 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 121x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 25.7 KB
    Aspect ratio: 1.00
Page 21: Found 3 image(s)
  Image 1:
    Dimensions: 918x444 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 893.9 KB
    Aspect ratio: 2.07
  Image 2:
    Dimensions: 918x526 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 350.0 KB
    Aspect ratio: 1.75
  Image 3:
    Dimensions: 621x917 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 25.1 KB
    Aspect ratio: 0.68
Page 22: Found 2 image(s)
  Image 1:
    Dimensions: 1117x847 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 2351.5 KB
    Aspect ratio: 1.32
  Image 2:
    Dimensions: 914x485 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 812.7 KB
    Aspect ratio: 1.88
Page 23: Found 3 image(s)
  Image 1:
    Dimensions: 441x330 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 305.9 KB
    Aspect ratio: 1.34
  Image 2:
    Dimensions: 917x408 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 916.2 KB
    Aspect ratio: 2.25
  Image 3:
    Dimensions: 441x446 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 396.8 KB
    Aspect ratio: 0.99
Page 24: Found 3 image(s)
  Image 1:
    Dimensions: 441x345 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 344.1 KB
    Aspect ratio: 1.28
  Image 2:
    Dimensions: 441x350 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 329.9 KB
    Aspect ratio: 1.26
  Image 3:
    Dimensions: 159x158 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 44.3 KB
    Aspect ratio: 1.01
Page 25: Found 4 image(s)
  Image 1:
    Dimensions: 1117x859 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1282.4 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 118x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 22.3 KB
    Aspect ratio: 0.98
  Image 3:
    Dimensions: 918x519 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 955.8 KB
    Aspect ratio: 1.77
  Image 4:
    Dimensions: 437x263 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 242.3 KB
    Aspect ratio: 1.66
Page 26: Found 5 image(s)
  Image 1:
    Dimensions: 121x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 25.7 KB
    Aspect ratio: 1.00
  Image 2:
    Dimensions: 121x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 19.0 KB
    Aspect ratio: 1.00
  Image 3:
    Dimensions: 924x702 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1490.5 KB
    Aspect ratio: 1.32
  Image 4:
    Dimensions: 914x254 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 284.9 KB
    Aspect ratio: 3.60
  Image 5:
    Dimensions: 117x118 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 26.2 KB
    Aspect ratio: 0.99
Page 27: Found 3 image(s)
  Image 1:
    Dimensions: 1116x861 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 2173.4 KB
    Aspect ratio: 1.30
  Image 2:
    Dimensions: 113x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 22.4 KB
    Aspect ratio: 0.93
  Image 3:
    Dimensions: 441x359 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 306.0 KB
    Aspect ratio: 1.23
Page 28: Found 2 image(s)
  Image 1:
    Dimensions: 919x435 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 984.7 KB
    Aspect ratio: 2.11
  Image 2:
    Dimensions: 1116x1553 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 2415.0 KB
    Aspect ratio: 0.72
Page 29: Found 3 image(s)
  Image 1:
    Dimensions: 1117x783 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 1403.9 KB
    Aspect ratio: 1.43
  Image 2:
    Dimensions: 918x421 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 868.8 KB
    Aspect ratio: 2.18
  Image 3:
    Dimensions: 121x121 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 28.0 KB
    Aspect ratio: 1.00
Page 30: Found 1 image(s)
  Image 1:
    Dimensions: 402x247 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 246.6 KB
    Aspect ratio: 1.63
Page 31: Found 2 image(s)
  Image 1:
    Dimensions: 526x390 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 555.9 KB
    Aspect ratio: 1.35
  Image 2:
    Dimensions: 442x483 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 570.2 KB
    Aspect ratio: 0.92
Page 32: Found 2 image(s)
  Image 1:
    Dimensions: 443x673 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 643.2 KB
    Aspect ratio: 0.66
  Image 2:
    Dimensions: 1346x1111 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 52.4 KB
    Aspect ratio: 1.21
Page 33: Found 1 image(s)
  Image 1:
    Dimensions: 2229x1243 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 4011.5 KB
    Aspect ratio: 1.79
Page 287: Found 1 image(s)
  Image 1:
    Dimensions: 1554x1114 px
    Colorspace: ICCBased(RGB,sRGB IEC61966-2.1)
    Size: 75.7 KB
    Aspect ratio: 1.39

Total images extracted: 133

In [65]:
image_metadata[0]

{'page': 1,
 'image_index': 0,
 'xref': 3834,
 'width': 2325,
 'height': 3234,
 'size_pixels': 7519050,
 'n': 3,
 'colorspace': 'ICCBased(RGB,sRGB IEC61966-2.1)',
 'alpha': 0,
 'uncompressed_bytes': 7299096,
 'hash': '50d19029508ebbf63f604ed452fb783e',
 'aspect_ratio': 0.7189239332096475}

In [66]:
# These packages are able to find images and extract image metadata; but
# these cannot provide the context of the images.
# So we will explore unstructured & docling to compare who provides the best results

In [67]:
# To install these packages, you will need a few additional tools and libraries, especially for handling PDFs and images. 
# Here are the installation instructions for both Unstructured and Docling.
# I am currently using a Linux system, so the instructions are for Linux. If you are using Windows or Mac, the installation process may vary slightly.

``` bash
sudo apt update

sudo apt install -y \
  libmagic1 \
  libmagic-dev \
  poppler-utils \
  tesseract-ocr \
  pandoc
  
```
----
``` bash
sudo apt install tesseract-ocr-eng
sudo apt install tesseract-ocr-hin   # Hindi
```
----
``` bash
file --version
pdftotext -v
tesseract --version
pandoc --version
```
----
``` bash
sudo apt install -y \
  ghostscript \
  libreoffice \
  unrtf
```
----
``` bash
pip install docling
pip install docling-core
pip install transformers torch
pip install docling-ibm-models[opencv-python-headless]
pip install easyocr

pip install unstructured
pip install "unstructured[all-docs]"
pip install unstructured-client
```
----

In [68]:
import json
import re
from pathlib import Path
from typing import Any

In [69]:
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions

In [70]:
URL_PATTERN = re.compile(
    r"""(?ix)\b(
        (?:https?://|www\.)
        [^\s<>()\[\]{}"']+
    )"""
)

In [71]:
def safe_get_page(item: Any) -> int | None:
    prov = getattr(item, "prov", None)
    if prov and len(prov) > 0:
        return getattr(prov[0], "page_no", None)
    return None

In [72]:
def safe_get_bbox(item: Any) -> dict | None:
    prov = getattr(item, "prov", None)
    if prov and len(prov) > 0 and getattr(prov[0], "bbox", None):
        bbox = prov[0].bbox
        return {
            "l": getattr(bbox, "l", None),
            "t": getattr(bbox, "t", None),
            "r": getattr(bbox, "r", None),
            "b": getattr(bbox, "b", None),
        }
    return None

In [73]:
def extract_urls_from_text(text: str) -> list[str]:
    if not text:
        return []
    return list({m.group(1) for m in URL_PATTERN.finditer(text)})

In [74]:
def normalize_docling_item(item: Any) -> list[dict]:
    """
    Returns one or more normalized records.
    A text item may also emit url records if URLs are found inside it.
    """
    out: list[dict] = []

    item_type = item.__class__.__name__
    page = safe_get_page(item)
    bbox = safe_get_bbox(item)

    # TEXT / FORMULA
    if item_type == "TextItem":
        label = str(getattr(item, "label", "")).upper()
        text = getattr(item, "text", "") or ""

        if "FORMULA" in label:
            # Formula enrichment may populate extra fields depending on version/model.
            # Keep raw text, and if enriched latex exists, capture it.
            latex = getattr(item, "latex", None) or getattr(item, "orig", None) or text
            out.append({
                "type": "latex",
                "page": page,
                "bbox": bbox,
                "content": latex,
                "raw": text,
            })
        else:
            out.append({
                "type": "text",
                "page": page,
                "bbox": bbox,
                "content": text,
                "raw": text,
            })

            for url in extract_urls_from_text(text):
                out.append({
                    "type": "url",
                    "page": page,
                    "bbox": bbox,
                    "content": url,
                    "raw": text,
                })

    # TABLE
    elif item_type == "TableItem":
        table_data = None
        try:
            # Often available via export methods or nested data
            if hasattr(item, "export_to_markdown"):
                table_data = item.export_to_markdown()
            elif hasattr(item, "data"):
                table_data = str(item.data)
        except Exception:
            table_data = None

        out.append({
            "type": "table",
            "page": page,
            "bbox": bbox,
            "content": table_data,
            "raw": item_type,
        })

    # IMAGE / PICTURE
    elif item_type == "PictureItem":
        out.append({
            "type": "image",
            "page": page,
            "bbox": bbox,
            "content": {
                "caption": getattr(item, "caption_text", None),
                "annotations": getattr(item, "annotations", None),
            },
            "raw": item_type,
        })

    return out

In [75]:
def run_docling(pdf_path: str) -> dict:
    pipeline_options = PdfPipelineOptions()

    # Turn on useful enrichments
    pipeline_options.do_formula_enrichment = False
    pipeline_options.do_picture_classification = True
    # optionally:
    # pipeline_options.do_picture_description = True

    converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
        }
    )

    result = converter.convert(pdf_path)
    doc = result.document

    records: list[dict] = []

    # DoclingDocument contains collections for texts/tables/pictures depending on version,
    # but walking exported dict is often the most version-tolerant method.
    doc_dict = doc.export_to_dict()

    # Version-tolerant traversal
    for key in ("texts", "tables", "pictures"):
        for item in doc_dict.get(key, []):
            label = str(item.get("label", "")).upper()
            page = None
            bbox = None

            prov = item.get("prov", [])
            if prov:
                page = prov[0].get("page_no")
                bbox = prov[0].get("bbox")

            if key == "texts":
                text = item.get("text", "")
                if "FORMULA" in label:
                    records.append({
                        "type": "latex",
                        "page": page,
                        "bbox": bbox,
                        "content": item.get("latex") or text,
                        "raw": text,
                    })
                else:
                    records.append({
                        "type": "text",
                        "page": page,
                        "bbox": bbox,
                        "content": text,
                        "raw": text,
                    })
                    for url in extract_urls_from_text(text):
                        records.append({
                            "type": "url",
                            "page": page,
                            "bbox": bbox,
                            "content": url,
                            "raw": text,
                        })

            elif key == "tables":
                records.append({
                    "type": "table",
                    "page": page,
                    "bbox": bbox,
                    "content": item,
                    "raw": "table",
                })

            elif key == "pictures":
                records.append({
                    "type": "image",
                    "page": page,
                    "bbox": bbox,
                    "content": item,
                    "raw": "picture",
                })

    return {
        "source": str(pdf_path),
        "records": records,
    }

In [76]:
data_directory

'../assets/data/'

In [77]:
filename

'Nestlé-India-AR-2024-25.pdf'

In [78]:
output = run_docling(data_directory + filename)

`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 360/360 [00:00<00:00, 20290.93it/s]
[INFO] 2026-03-30 14:58:53,599 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-03-30 14:58:53,604 [RapidOCR] download_file.py:60: File exists and is valid: /home/pritesh-jha/projects/poc-to-prod/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_det_infer.onnx
[INFO] 2026-03-30 14:58:53,604 [RapidOCR] main.py:53: Using /home/pritesh-jha/projects/poc-to-prod/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_det_infer.onnx
[INFO] 2026-03-30 14:58:53,662 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-03-30 14:58:53,663 [RapidOCR] download_file.py:60: File exists and is valid: /home/pritesh-jha/projects/poc-to-prod/.venv/lib/python3.12/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_infer.onnx
[INFO] 2026-03-30 14:58:53,663 [RapidOCR] main.py:53: Using /home/pritesh-jha/projects/poc-to-prod/.venv/lib/python3.12/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_infer.onnx
[INFO] 2026-03-30 14:58:53,685 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-03-30 14:58:53,693 [RapidOCR] download_file.py:60: File exists and is valid: /home/pritesh-jha/projects/poc-to-prod/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_rec_infer.onnx
[INFO] 2026-03-30 14:58:53,693 [RapidOCR] main.py:53: Using /home/pritesh-jha/projects/poc-to-prod/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_rec_infer.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 7772.59it/s]
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:16,303 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:19,451 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:28,901 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:30,435 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:32,283 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:34,082 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:34,220 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:35,476 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:38,820 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:39,691 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:42,224 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:42,303 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
RapidOCR returned empty result!
[WARNING] 2026-03-30 14:59:47,589 [RapidOCR] main.py:125: The text detection result is empty
RapidOCR returned empty result!

In [79]:
output

{'source': '../assets/data/Nestlé-India-AR-2024-25.pdf',
 'records': [{'type': 'text',
   'page': 1,
   'bbox': {'l': 36.0,
    't': 737.5052000000001,
    'r': 142.43599999999998,
    'b': 716.0134779886148,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Nestlé India Limited Annual Report 2024-25',
   'raw': 'Nestlé India Limited Annual Report 2024-25'},
  {'type': 'text',
   'page': 1,
   'bbox': {'l': 36.0,
    't': 527.881945,
    'r': 202.80589640000002,
    'b': 398.52100225000004,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Adversity Makes Us Stronger',
   'raw': 'Adversity Makes Us Stronger'},
  {'type': 'text',
   'page': 1,
   'bbox': {'l': 444.4138590494792,
    't': 698.3165283203125,
    'r': 505.8055419921875,
    'b': 680.7610880533854,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Nestle.',
   'raw': 'Nestle.'},
  {'type': 'text',
   'page': 1,
   'bbox': {'l': 425.4944254557292,
    't': 675.2993876139323,
    'r': 521.25,
    'b': 662.8155212402344,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Good food, Good life',
   'raw': 'Good food, Good life'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 366.5,
    't': 697.1431452433268,
    'r': 391.359375,
    'b': 692.7268142700195,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Nuati-liciens',
   'raw': 'Nuati-liciens'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 370.53125,
    't': 679.4778238932291,
    'r': 392.703125,
    'b': 672.6834665934244,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'BESAN',
   'raw': 'BESAN'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 64.15625,
    't': 668.2671356201172,
    'r': 111.1875,
    'b': 657.0564524332682,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'munch',
   'raw': 'munch'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 70.5390625,
    't': 657.7358856201172,
    'r': 105.140625,
    'b': 644.8266143798828,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'CHOCO',
   'raw': 'CHOCO'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 379.6015625,
    't': 659.4344736735026,
    'r': 391.0234375,
    'b': 654.3387095133463,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'RICHN',
   'raw': 'RICHN'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 400.765625,
    't': 659.7741902669271,
    'r': 422.6015625,
    'b': 648.9032236735026,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'SPICY',
   'raw': 'SPICY'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 454.1796875,
    't': 660.1139119466146,
    'r': 471.3125,
    'b': 654.3387095133463,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Maggi',
   'raw': 'Maggi'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 378.59375,
    't': 654.3387095133463,
    'r': 392.3671875,
    'b': 648.5635070800781,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'PROTEIN',
   'raw': 'PROTEIN'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 74.5703125,
    't': 650.9415334065756,
    'r': 100.4375,
    'b': 635.6542358398438,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'FILLS',
   'raw': 'FILLS'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 378.59375,
    't': 648.5635070800781,
    'r': 391.6953125,
    'b': 642.7883046468098,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'FiBeR',
   'raw': 'FiBeR'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 395.7265625,
    't': 649.9223785400391,
    'r': 427.3046875,
    'b': 642.7883046468098,
    'coord_origin': 'BOTTOMLEFT'},
   'content': "MANCHURIRN'",
   'raw': "MANCHURIRN'"},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 451.4921875,
    't': 643.1280212402344,
    'r': 474.671875,
    'b': 633.9556477864583,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'SPICY',
   'raw': 'SPICY'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 96.40625,
    't': 631.577616373698,
    'r': 108.5,
    'b': 620.0272115071614,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Melty',
   'raw': 'Melty'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 449.4765625,
    't': 632.9364929199219,
    'r': 477.359375,
    'b': 624.7832641601562,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'GARLIC',
   'raw': 'GARLIC'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 62.140625,
    't': 623.0846761067708,
    'r': 75.9140625,
    'b': 619.3477783203125,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'CRUNCKY',
   'raw': 'CRUNCKY'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 113.5390625,
    't': 512.6764119466146,
    'r': 228.765625,
    'b': 500.78629557291663,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'NESCAFE NESCAFENESCAFE',
   'raw': 'NESCAFE NESCAFENESCAFE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 72.5546875,
    't': 495.0110880533854,
    'r': 105.4765625,
    'b': 484.4798380533854,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'NESCAFE',
   'raw': 'NESCAFE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 233.46875,
    't': 496.70967610677087,
    'r': 270.421875,
    'b': 485.1592814127604,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'NESCAFE',
   'raw': 'NESCAFE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 333.2421875,
    't': 460.6995849609375,
    'r': 373.5546875,
    'b': 450.508056640625,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'NESCAFE',
   'raw': 'NESCAFE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 116.8984375,
    't': 450.8477783203125,
    'r': 148.140625,
    'b': 444.3931477864583,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'CARAMEL',
   'raw': 'CARAMEL'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 159.8984375,
    't': 451.1875,
    'r': 184.0859375,
    'b': 444.3931477864583,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'CHOCO',
   'raw': 'CHOCO'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 197.859375,
    't': 450.8477783203125,
    'r': 226.4140625,
    'b': 444.3931477864583,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'CLASSIC',
   'raw': 'CLASSIC'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 337.609375,
    't': 451.86692301432294,
    'r': 367.84375,
    'b': 445.07257080078125,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'ICEROAST',
   'raw': 'ICEROAST'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 84.3125,
    't': 442.35483805338544,
    'r': 96.40625,
    'b': 437.2590738932292,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'ICED',
   'raw': 'ICED'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 124.625,
    't': 445.41229248046875,
    'r': 141.421875,
    'b': 439.6370849609375,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'LATTE',
   'raw': 'LATTE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 163.2578125,
    't': 445.75201416015625,
    'r': 180.0546875,
    'b': 439.976806640625,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'LATTE',
   'raw': 'LATTE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 203.90625,
    't': 445.41229248046875,
    'r': 220.3671875,
    'b': 439.6370849609375,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'LATTE',
   'raw': 'LATTE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 244.5546875,
    't': 442.69455973307294,
    'r': 258.328125,
    'b': 436.9193522135417,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'ICED',
   'raw': 'ICED'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 80.6171875,
    't': 438.61794026692706,
    'r': 100.1015625,
    'b': 432.5030110677083,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'LATTE',
   'raw': 'LATTE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 238.84375,
    't': 438.95766194661456,
    'r': 264.7109375,
    'b': 431.82358805338544,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'FRAPPE',
   'raw': 'FRAPPE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 115.21875,
    't': 367.2772216796875,
    'r': 130.0,
    'b': 356.40625,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'at',
   'raw': 'at'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 208.609375,
    't': 362.8608805338542,
    'r': 224.734375,
    'b': 336.3629150390625,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'EasyPourPack',
   'raw': 'EasyPourPack'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 91.703125,
    't': 336.70263671875,
    'r': 120.2578125,
    'b': 327.5302327473958,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'DOUBLE',
   'raw': 'DOUBLE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 203.90625,
    't': 334.664306640625,
    'r': 226.4140625,
    'b': 325.491943359375,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Nestle.',
   'raw': 'Nestle.'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 83.9765625,
    't': 327.8699544270833,
    'r': 129.6640625,
    'b': 318.6975911458333,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'CHOCOLATE',
   'raw': 'CHOCOLATE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 178.0390625,
    't': 324.4727783203125,
    'r': 240.859375,
    'b': 314.960693359375,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Milkmaid',
   'raw': 'Milkmaid'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 87.671875,
    't': 319.3769938151042,
    'r': 123.28125,
    'b': 313.9415283203125,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'COATED HAFER',
   'raw': 'COATED HAFER'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 215.6640625,
    't': 312.5826416015625,
    'r': 238.5078125,
    'b': 306.4677327473958,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'mini',
   'raw': 'mini'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 181.734375,
    't': 242.94051106770826,
    'r': 226.75,
    'b': 236.14615885416674,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '100-recipes@milkmaidin',
   'raw': '100-recipes@milkmaidin'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 58.109375,
    't': 183.15018717447913,
    'r': 141.7578125,
    'b': 171.93949381510413,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'munch',
   'raw': 'munch'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 110.515625,
    't': 171.26009114583337,
    'r': 152.171875,
    'b': 155.9727783203125,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'max',
   'raw': 'max'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 49.7109375,
    't': 166.84375,
    'r': 110.8515625,
    'b': 160.04939778645837,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'XrRUCHOCTASTE',
   'raw': 'XrRUCHOCTASTE'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 71.546875,
    't': 139.66634114583337,
    'r': 126.9765625,
    'b': 126.75703938802087,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'munch',
   'raw': 'munch'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 612.533,
    't': 564.736,
    'r': 804.8690000000001,
    'b': 394.5484320855614,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Every morning as a new day dawns….8,629 employees in our factories, fields and offices, work with indefatigable zeal and a singular PURPOSE of serving our beloved consumers, with a single pursuit of bringing products that are of unimpeachable quality.',
   'raw': 'Every morning as a new day dawns….8,629 employees in our factories, fields and offices, work with indefatigable zeal and a singular PURPOSE of serving our beloved consumers, with a single pursuit of bringing products that are of unimpeachable quality.'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 612.533,
    't': 376.567,
    'r': 701.8030000000001,
    'b': 367.69781130355517,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Suresh Narayanan',
   'raw': 'Suresh Narayanan'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 612.533,
    't': 363.47950000000003,
    'r': 744.0960000000003,
    'b': 355.9033178838951,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Chairman and Managing Director',
   'raw': 'Chairman and Managing Director'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 612.533,
    't': 202.11829999999998,
    'r': 686.7393000000001,
    'b': 195.9098679124886,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Cautionary Statement',
   'raw': 'Cautionary Statement'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 612.533,
    't': 187.44629999999995,
    'r': 779.3129000000006,
    'b': 100.18909119850184,
    'coord_origin': 'BOTTOMLEFT'},
   'content': "Statements in this Annual Report, particularly those which relate to Management Discussion and Analysis as explained in the Corporate Governance Report, describing the Company's objectives, projections, estimates and expectations may constitute 'forward looking statements' within the meaning of applicable laws and regulations. Actual results might differ materially from those either expressed or implied in the statement depending on the circumstances.",
   'raw': "Statements in this Annual Report, particularly those which relate to Management Discussion and Analysis as explained in the Corporate Governance Report, describing the Company's objectives, projections, estimates and expectations may constitute 'forward looking statements' within the meaning of applicable laws and regulations. Actual results might differ materially from those either expressed or implied in the statement depending on the circumstances."},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 875.6636,
    't': 715.6875,
    'r': 995.1475999999999,
    'b': 683.7743181818182,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Contents',
   'raw': 'Contents'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 906.3014,
    't': 630.7391,
    'r': 1024.2479,
    'b': 621.426451868733,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Annual Report 2024-25',
   'raw': 'Annual Report 2024-25'},
  {'type': 'text',
   'page': 2,
   'bbox': {'l': 906.3014,
    't': 277.176,
    'r': 1070.9099,
    'b': 267.8633518687329,
    'coord_origin': 'BOTTOMLEFT'},
   'content': "Annexures to the Board's Report",
   'raw': "Annexures to the Board's Report"},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 42.5197,
    't': 716.1374000000001,
    'r': 217.05769999999998,
    'b': 693.088990909091,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Board of Directors',
   'raw': 'Board of Directors'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 202.9941,
    't': 254.16139999999996,
    'r': 211.4341,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '01',
   'raw': '01'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 330.9909,
    't': 254.16139999999996,
    'r': 340.5509,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '02',
   'raw': '02'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 423.8559,
    't': 254.16139999999996,
    'r': 433.5679,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '03',
   'raw': '03'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 465.4766,
    't': 254.16139999999996,
    'r': 475.3566,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '04',
   'raw': '04'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 656.5303,
    't': 254.16139999999996,
    'r': 666.1703,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '05',
   'raw': '05'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 730.6544,
    't': 254.16139999999996,
    'r': 740.5344,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '06',
   'raw': '06'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 849.9332,
    't': 254.16139999999996,
    'r': 859.1092000000001,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '07',
   'raw': '07'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 962.9911,
    't': 254.16139999999996,
    'r': 972.8951,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '08',
   'raw': '08'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 1002.9597,
    't': 254.16139999999996,
    'r': 1012.8317,
    'b': 247.06604904284416,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '09',
   'raw': '09'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 948.054443359375,
    't': 546.9673258463541,
    'r': 988.9574381510416,
    'b': 524.4289754231771,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Nestle',
   'raw': 'Nestle'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 200.39919999999998,
    't': 151.414,
    'r': 332.0073,
    'b': 123.51547565543069,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Mr. Sidharth Kumar Birla Independent Non-Executive Director 01__',
   'raw': 'Mr. Sidharth Kumar Birla Independent Non-Executive Director 01__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 200.39919999999998,
    't': 108.15779999999995,
    'r': 309.51039999999995,
    'b': 80.25927565543066,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Ms. Alpana Parida Independent Non-Executive Director 02__',
   'raw': 'Ms. Alpana Parida Independent Non-Executive Director 02__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 358.2776,
    't': 151.414,
    'r': 467.3888,
    'b': 123.51547565543069,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Ms. Anjali Bansal Independent Non-Executive Director 03__',
   'raw': 'Ms. Anjali Bansal Independent Non-Executive Director 03__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 358.2776,
    't': 108.15779999999995,
    'r': 478.75359999999995,
    'b': 80.25927565543066,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Mr. Suresh Narayanan Chairman and Managing Director 04__',
   'raw': 'Mr. Suresh Narayanan Chairman and Managing Director 04__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 612.5341,
    't': 151.414,
    'r': 724.7112000000002,
    'b': 123.51547565543069,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Ms. Suneeta Reddy Independent Non-Executive Director 05__',
   'raw': 'Ms. Suneeta Reddy Independent Non-Executive Director 05__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 612.5341,
    't': 108.15779999999995,
    'r': 729.5721000000003,
    'b': 80.25927565543066,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Ms. Svetlana Boldina Executive Director F&C and CFO 06__',
   'raw': 'Ms. Svetlana Boldina Executive Director F&C and CFO 06__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 770.4125,
    't': 151.414,
    'r': 879.5237000000003,
    'b': 123.51547565543069,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Mr. P. R. Ramesh Independent Non-Executive Director 07__',
   'raw': 'Mr. P. R. Ramesh Independent Non-Executive Director 07__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 770.4125,
    't': 108.15779999999995,
    'r': 886.1005000000002,
    'b': 80.25927565543066,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Mr. Satish Srinivasan Executive Director Technical 08__',
   'raw': 'Mr. Satish Srinivasan Executive Director Technical 08__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 928.2909,
    't': 151.414,
    'r': 1050.2510000000002,
    'b': 123.51547565543069,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Mr. Pramod Kumar Rai Company Secretary and Compliance Officer 09__',
   'raw': 'Mr. Pramod Kumar Rai Company Secretary and Compliance Officer 09__'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 974.8853,
    't': 741.9336000000001,
    'r': 1069.2656000000002,
    'b': 735.6943911985019,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Adversity Makes Us Stronger',
   'raw': 'Adversity Makes Us Stronger'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 45.4054,
    't': 31.933599999999956,
    'r': 55.64789999999999,
    'b': 24.394789608021824,
    'coord_origin': 'BOTTOMLEFT'},
   'content': '02',
   'raw': '02'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 68.5335,
    't': 30.461099999999988,
    'r': 120.64850000000003,
    'b': 24.255759090909123,
    'coord_origin': 'BOTTOMLEFT'},
   'content': 'Nestlé India Limited',
   'raw': 'Nestlé India Limited'},
  {'type': 'text',
   'page': 3,
   'bbox': {'l': 968.0989,
    't': 30.461099999999988,

In [80]:
output.keys()

dict_keys(['source', 'records'])

In [81]:
types_list = []
page_list = []
content_list = []

for record in output["records"]:
    record_type = record.get("type")
    types_list.append(record_type)
    page = record.get("page")
    page_list.append(page)
    content = record.get("content")
    content_list.append(content)

In [82]:
set(types_list)

{'image', 'table', 'text', 'url'}

In [83]:
df = pd.DataFrame(list(zip(types_list, page_list, content_list)), columns=["type", "page", "content"])

In [84]:
df.head(2)

   type  page                                     content
0  text     1  Nestlé India Limited Annual Report 2024-25
1  text     1                 Adversity Makes Us Stronger

In [85]:
df[df["type"] == "table"].head(5)

       type  page                                            content
4829  table     2  {'self_ref': '#/tables/0', 'parent': {'$ref': ...
4830  table     2  {'self_ref': '#/tables/1', 'parent': {'$ref': ...
4831  table     7  {'self_ref': '#/tables/2', 'parent': {'$ref': ...
4832  table    10  {'self_ref': '#/tables/3', 'parent': {'$ref': ...
4833  table    10  {'self_ref': '#/tables/4', 'parent': {'$ref': ...

In [86]:
df[df["type"] == "image"].head(5)

       type  page                                            content
5148  image     1  {'self_ref': '#/pictures/0', 'parent': {'$ref'...
5149  image     2  {'self_ref': '#/pictures/1', 'parent': {'$ref'...
5150  image     2  {'self_ref': '#/pictures/2', 'parent': {'$ref'...
5151  image     3  {'self_ref': '#/pictures/3', 'parent': {'$ref'...
5152  image     5  {'self_ref': '#/pictures/4', 'parent': {'$ref'...

In [87]:
df[df["type"] == "url"].head(5)

     type  page                                            content
1373  url    34                                       https://www.
1493  url    36                                      www.nestle.in
1773  url    39          https://www.nestle.in/investors/policies.
1918  url    45          https://www.nestle.in/investors/policies.
1923  url    45  https://www.nestle.in/about-us/our-leadership-...

In [88]:
# The above output shows that we are able to extract text, tables, images, and URLs from the PDF using Docling.
# The "content" field contains the extracted data, which can be further processed or analyzed as needed.

In [89]:
# Lets check on example of a table content to see how it looks like.
df[df["type"] == "table"].iloc[0]["content"]

{'self_ref': '#/tables/0',
 'parent': {'$ref': '#/body'},
 'children': [],
 'content_layer': 'body',
 'label': 'document_index',
 'prov': [{'page_no': 2,
   'bbox': {'l': 873.1370239257812,
    't': 604.2259368896484,
    'r': 1027.7086181640625,
    'b': 302.1272888183594,
    'coord_origin': 'BOTTOMLEFT'},
   'charspan': [0, 0]}],
 'captions': [],
 'references': [],
 'footnotes': [],
 'data': {'table_cells': [{'bbox': {'l': 875.6636,
     't': 173.57579999999996,
     'r': 885.5405999999999,
     'b': 181.15198211610482,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 0,
    'end_row_offset_idx': 1,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '02',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 188.19579999999996,
     'r': 885.8380999999999,
     'b': 195.77198211610482,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 1,
    'end_row_offset_idx': 2,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '04',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 217.42729999999995,
     'r': 884.4355999999999,
     'b': 225.0034821161048,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 3,
    'end_row_offset_idx': 4,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '10',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 319.09579999999994,
     'r': 885.5405999999999,
     'b': 326.67198211610486,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 10,
    'end_row_offset_idx': 11,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '20',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 202.81579999999997,
     'r': 885.9571,
     'b': 210.39198211610483,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 2,
    'end_row_offset_idx': 3,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '06',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 333.71579999999994,
     'r': 885.7531,
     'b': 341.29198211610486,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 11,
    'end_row_offset_idx': 12,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '36',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 232.04729999999995,
     'r': 884.0106,
     'b': 239.6234821161048,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 4,
    'end_row_offset_idx': 5,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '12',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 348.3272999999999,
     'r': 885.8380999999999,
     'b': 355.90348211610484,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 12,
    'end_row_offset_idx': 13,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '40',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 449.2052999999999,
     'r': 886.0081,
     'b': 456.7814821161048,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 19,
    'end_row_offset_idx': 20,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '68',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 434.2197999999999,
     'r': 885.1326,
     'b': 441.7959821161048,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 18,
    'end_row_offset_idx': 19,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '67',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 420.6962999999999,
     'r': 885.8296,
     'b': 428.2724821161048,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 17,
    'end_row_offset_idx': 18,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '64',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 246.66729999999995,
     'r': 884.2316,
     'b': 254.24348211610481,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 5,
    'end_row_offset_idx': 6,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '13',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 392.18729999999994,
     'r': 885.5831,
     'b': 399.76348211610485,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 15,
    'end_row_offset_idx': 16,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '54',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 362.95579999999995,
     'r': 885.8296,
     'b': 370.53198211610487,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 13,
    'end_row_offset_idx': 14,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '46',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 304.48429999999996,
     'r': 884.4866,
     'b': 312.0604821161049,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 9,
    'end_row_offset_idx': 10,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '18',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 289.78779999999995,
     'r': 883.6111,
     'b': 297.36398211610486,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 8,
    'end_row_offset_idx': 9,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '17',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 275.17629999999997,
     'r': 884.4271,
     'b': 282.7524821161049,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 7,
    'end_row_offset_idx': 8,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '16',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 876.0206,
     't': 260.5648,
     'r': 884.6650999999999,
     'b': 268.1409821161049,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 6,
    'end_row_offset_idx': 7,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '14',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 406.80729999999994,
     'r': 885.5321,
     'b': 414.38348211610486,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 16,
    'end_row_offset_idx': 17,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '62',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 377.57579999999996,
     'r': 885.7105999999999,
     'b': 385.1519821161049,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 14,
    'end_row_offset_idx': 15,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '50',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 875.6636,
     't': 463.19629999999995,
     'r': 885.8126,
     'b': 470.77248211610487,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 20,
    'end_row_offset_idx': 21,
    'start_col_offset_idx': 0,
    'end_col_offset_idx': 1,
    'text': '83',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 173.57580000000007,
     'r': 973.4766,
     'b': 180.70632434456934,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 0,
    'end_row_offset_idx': 1,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Board of Directors',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 188.19360000000006,
     'r': 1012.7118969199988,
     'b': 195.32412434456933,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 1,
    'end_row_offset_idx': 2,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Adversity Makes Us Stronger',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 217.42910000000006,
     'r': 1028.3481768000015,
     'b': 224.55962434456933,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 3,
    'end_row_offset_idx': 4,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'The Decade That Was (2015-2025)',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 319.0954,
     'r': 968.7333999999998,
     'b': 326.2259243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 10,
    'end_row_offset_idx': 11,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Product Portfolio',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 202.80740000000003,
     'r': 984.2453999999999,
     'b': 209.9379243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 2,
    'end_row_offset_idx': 3,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': "Chairman's Message",
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 333.71139999999997,
     'r': 955.5573999999999,
     'b': 340.8419243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 11,
    'end_row_offset_idx': 12,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'IT Integration',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 232.04740000000004,
     'r': 978.2614000000001,
     'b': 239.1779243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 4,
    'end_row_offset_idx': 5,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': "Nestlé's India Story",
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 348.3354,
     'r': 1021.5734000000001,
     'b': 355.4659243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 12,
    'end_row_offset_idx': 13,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Corporate Social Responsibility',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 449.2074,
     'r': 960.9974,
     'b': 456.33792434456933,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 19,
    'end_row_offset_idx': 20,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': "Board's Report",
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 434.2234,
     'r': 988.6374,
     'b': 441.35392434456935,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 18,
    'end_row_offset_idx': 19,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Corporate Information',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 420.6954,
     'r': 990.8854000000001,
     'b': 427.82592434456933,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 17,
    'end_row_offset_idx': 18,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Risk and Opportunities',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 246.66340000000002,
     'r': 993.7094000000002,
     'b': 253.7939243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 5,
    'end_row_offset_idx': 6,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Brand Footprint in India',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 392.18339999999995,
     'r': 929.6694,
     'b': 399.3139243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 15,
    'end_row_offset_idx': 16,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Planet',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 362.9514,
     'r': 931.5414,
     'b': 370.0819243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 13,
    'end_row_offset_idx': 14,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'People',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 304.4794,
     'r': 926.2374,
     'b': 311.6099243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 9,
    'end_row_offset_idx': 10,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Sales',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 289.7834,
     'r': 1013.5574000000004,
     'b': 296.9139243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 8,
    'end_row_offset_idx': 9,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': '10 - Year Financial Highlights',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 275.17539999999997,
     'r': 995.9014000000002,
     'b': 282.3059243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 7,
    'end_row_offset_idx': 8,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Nestlé India in Numbers',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.6533999999999,
     't': 260.5594,
     'r': 954.6533999999999,
     'b': 267.6899243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 6,
    'end_row_offset_idx': 7,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'NESPRESSO',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 406.8074,
     'r': 1000.9413999999999,
     'b': 413.9379243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 16,
    'end_row_offset_idx': 17,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Awards and Recognitions',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 377.5754,
     'r': 952.9334,
     'b': 384.7059243445693,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 14,
    'end_row_offset_idx': 15,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Partnerships',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False},
   {'bbox': {'l': 906.3014,
     't': 463.1994,
     'r': 969.3893999999998,
     'b': 470.32992434456935,
     'coord_origin': 'TOPLEFT'},
    'row_span': 1,
    'col_span': 1,
    'start_row_offset_idx': 20,
    'end_row_offset_idx': 21,
    'start_col_offset_idx': 1,
    'end_col_offset_idx': 2,
    'text': 'Annual Accounts',
    'column_header': False,
    'row_header': False,
    'row_section': False,
    'fillable': False}],
  'num_rows': 21,
  'num_cols': 2,
  'grid': [[{'bbox': {'l': 875.6636,
      't': 173.57579999999996,
      'r': 885.5405999999999,
      'b': 181.15198211610482,
      'coord_origin': 'TOPLEFT'},
     'row_span': 1,
     'col_span': 1,
     'start_row_offset_idx': 0,
     'end_row_offset_idx': 1,
     'start_col_offset_idx': 0,
     'end_col_offset_idx': 1,
     'text': '02',
     'column_header': False,
     'row_header': False,
     'row_section': False,
     'fillable': False},
    {'bbox': {'l': 906.3014,
      't': 173.57580000000007,
      'r': 973.4766,
      'b': 180.70632434456934,
      'coord_origin': 'TOPLEFT'},
     'row_span': 1,
     'col_span': 1,
     'start_row_offset_idx': 0,
     'end_row_offset_idx': 1,
     'start_col_offset_idx': 1,
     'end_col_offset_idx': 2,
     'text': 'Board of Directors',
     'column_header': False,
     'row_header': False,
     'row_section': False,
     'fillable': False}],
   [{'bbox': {'l': 875.6636,
      't': 188.19579999999996,
      'r': 885.8380999999999,
      'b': 195.77198211610482,
      'coord_origin': 'TOPLEFT'},
     'row_span': 1,
     'col_span': 1,
     'start_row_offset_idx': 1,
     'end_row_offset_idx': 2,
     'start_col_offset_idx': 0,
     'end_col_offset_idx': 1,
     'text': '04',
     'column_header': False,
     'row_header': False,
     'row_section': False,
     'fillable': False},
    {'bbox': {'l': 906.3014,
      't': 188.19360000000006,
      'r': 1012.7118969199988,
      'b': 195.32412434456933,

In [91]:
def reconstruct_table(table_content: dict) -> pd.DataFrame:
    """
    Reconstruct a pandas DataFrame from Docling's extracted table content.

    Each cell in `data.table_cells` carries its grid position via
    start_row_offset_idx / start_col_offset_idx, so we can place every
    cell into the correct slot of a 2-D grid and then build a DataFrame.
    """
    cells = table_content["data"]["table_cells"]

    # Determine grid dimensions
    num_rows = max(c["end_row_offset_idx"] for c in cells)
    num_cols = max(c["end_col_offset_idx"] for c in cells)

    # Build an empty grid
    grid = [[""] * num_cols for _ in range(num_rows)]

    # Track which rows are purely column-header rows
    header_rows = set()

    for cell in cells:
        r = cell["start_row_offset_idx"]
        c = cell["start_col_offset_idx"]
        grid[r][c] = cell["text"]
        if cell.get("column_header"):
            header_rows.add(r)

    if header_rows:
        # Use the last header row as column names
        header_row_idx = max(header_rows)
        columns = grid[header_row_idx]
        data_rows = [grid[i] for i in range(num_rows) if i not in header_rows]
    else:
        columns = [f"col_{i}" for i in range(num_cols)]
        data_rows = grid

    return pd.DataFrame(data_rows, columns=columns)

In [94]:
# Get the first extracted table and reconstruct it

table_content = df[df["type"] == "table"].iloc[5]["content"]

reconstructed_df = reconstruct_table(table_content)

In [95]:
reconstructed_df

                                         Particulars 2024-25 2023-24 ^
0  Operating Profit Margin (%) (Profit From Opera...    21.5      22.0
1  Net Profit Margin (%) (Profit after Tax / Sale...    16.5      16.2
2  Return on Net Worth (%) (Profit after Tax / Av...    88.9     108.5
3  Current Ratio (Current Assets / Current Liabil...     0.8       0.9
4  Inventory Turnover Ratio (Sale of Products / A...     8.1       9.7
5  Debtors Turnover Ratio (Sale of Products / Ave...    60.5      78.9
6                  Debt Equity ratio (Debt / Equity)     0.3       0.1
7  Interest Coverage Ratio (Interest cost / Earni...    95.0     178.5

In [96]:
# Here we can see that the table has been reconstructed successfully with the correct column headers and data rows.
# Based on this we can be confident that we can extract tables from complex PDFs and;
# reconstruct them into structured DataFrames for further analysis or integration into RAG pipelines.

The extracted table content uses `data.table_cells` — a flat list of cell objects each with:
- `start_row_offset_idx` / `start_col_offset_idx`: grid position
- `text`: cell content
- `column_header` / `row_header`: flags for header cells